### ISSUE TITLE
Inheritance support

### ISSUE THREAD

**Issue by a8t3r** [arnaudroger/SimpleFlatMapper#113]
I've got some ideas for library improvement.
I'm interesting in your opinion about this cases

### Inheritance support

`class Person`
`class Student extends Person`
`class Professor extends Person`

> select *, if(condition, 'student', 'proff') as discriminator_field from person left join student ...
> ===> returns list of Persons (students and professors)

Sometimes i want query class hierarchy with different instances of base class.
Required type can be distinguished by some discriminator field, like `discriminator_field` in my case

**Comment by arnaudroger** [comment]
those would be nice, but not trivial to implement. 
for the discriminator we could have a special mapper that would delegate to the right type depending on the value of the discriminator.

**Comment by arnaudroger** [comment]
the 1-n support is harder to do 
we would need to way to indicate which field indicates a change of professor. and then figure out how to manage the list. might be possible with a wrapper mapper.

**Comment by arnaudroger** [comment]
I thought a bit more about the 1 -n and I think i might have a way to do it. I will split the ticket in 2. and schedule those 2 for 1.6.0. I would like to clean up the toString and the doc before starting  though.

**Comment by arnaudroger** [comment]
So for that one as  start we need a Mapper that can delegate between different mapper on a discrimination expression.

**Comment by arnaudroger** [comment]
```java
        JdbcMapper<JoinJdbcMapperTest.Person> mapper =
                JdbcMapperFactoryHelper.asm()
                .addKeys("id", "students_id")
                .<JoinJdbcMapperTest.Person>newDiscriminator("person_type")
                .when("student", JoinJdbcMapperTest.StudentGS.class)
                        .addMapping("person_type")
                        .addMapping("id")
                        .addMapping("name")
                .when("professor", JoinJdbcMapperTest.ProfessorGS.class)
                .mapper();
```
