### ISSUE TITLE
sfm parse csv content issue

### ISSUE THREAD

**Issue by oyxiaogua** [arnaudroger/SimpleFlatMapper#264]
hello,sir
       i'm user sfm code
          Iterator<String[]> it = CsvParser.iterator(toReader(input)); 
       parse csv content          
         1993,Chevy,"Venture ""Extended Edition""","",4900.00
      result is : 
         1993, Chevy, Venture "Extended Edition", ", 4900.00,
     i think the correct result is 
         1993, Chevy, Venture "Extended Edition",, 4900.00

**Comment by arnaudroger** [comment]
Jsut reproduced the issue will issue a fix asap

**Comment by arnaudroger** [comment]
Thanks for the bug report, I'm suprise it never came up before. It's fixed in 2.6.5 that should be available in central maven in the next 10-30 minutes.
