### ISSUE TITLE
Separator for CsvWriter

### ISSUE THREAD

**Issue by AlexeyRaga** [arnaudroger/SimpleFlatMapper#272]
Is there a way to specify separator for CsvWriter?
I see that Parser can do that, what about writer?

**Comment by arnaudroger** [comment]
not at the minute will add that.

**Comment by arnaudroger** [comment]
actually there is a way right now. you can change the CellWriter to use a different separator. not as nice as having a specific method in the dsl. I'll add something to make it easier.

 CsvWriter.from(DbObject.class).cellWriter(new CsvCellWriter('\t', '"', false, "\r\n")).to(sw)

**Comment by arnaudroger** [comment]
you can now just do 

CsvWriter.from(DbObject.class).separator('\t').to(sw)

2.7.3 is being pushed
