### ISSUE TITLE
SimpleFlatMapper trying to joda time classes, need it to use java.time classes

### ISSUE THREAD

**Issue by DanielJoyce** [arnaudroger/SimpleFlatMapper#285]
Looked in docs, found no documentation on how to configure this. I am using JDK8, but out of the box it seems SimpleFlatMapper tries to use joda time classes first, which causes it to blow up with a class not found exception.

I have confirmed I am referrring to the jdk 8 artifact.

**Comment by DanielJoyce** [comment]
I am using this to talk to a database.

**Comment by DanielJoyce** [comment]
https://github.com/arnaudroger/SimpleFlatMapper/blob/master/sfm/src/main/java/org/sfm/jdbc/impl/PreparedStatementSetterFactory.java

Line 426+

`

        if (setter == null) {
            setter = jodaTimeFieldMapperToSourceFactory.indexedSetter(arg);  <-- Sets setter
        }

        //IFJAVA8_START
        if (setter == null) {  <-- Always false at this point!
            setter = javaTimeFieldMapperToSourceFactory.indexedSetter(arg);  <-- Never used!
        }
        //IFJAVA8_END

`

**Comment by DanielJoyce** [comment]
And the JodaTime factory at line 279 will blow up if the joda-time jar is not present. So even if not using Joda time classes, you need to have the jar present... :P

**Comment by arnaudroger** [comment]
Would you have the exception it fails with?

**Comment by arnaudroger** [comment]
I see. Very good point will get it fixed asap

**Comment by arnaudroger** [comment]
The ps setting part at the minute needs the Joda time lib to run in the class path. It should not.

**Comment by arnaudroger** [comment]
releasing 2.7.5  that should fix that.
should be available in maven central in the next 20-30 minutes.

**Comment by DanielJoyce** [comment]
Yeah I messed up. That's not the exact error. The error is when the class i
s tested against the joda time classes in the joda time factory.

Jumped the gun a smidge.

On Mon, Feb 8, 2016, 17:52 Arnaud Roger <notifications@github.com> wrote:

> releasing 2.7.5 that should fix that.
> should be available in maven central in the next 20-30 minutes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arnaudroger/SimpleFlatMapper/issues/285#issuecomment-181666203>
> .
>
-- 
Daniel Joyce

The meek shall inherit the Earth, for the brave will be among the stars.

**Comment by arnaudroger** [comment]
it's available in maven central.
