### ISSUE TITLE
no UUID PreparedStatement Setter

### ISSUE THREAD

**Issue by DanielJoyce** [arnaudroger/SimpleFlatMapper#286]
I am using Immutables.org to create immutable objects, and have it set up to create a static factory method called 'of' which takes the same parameters a public constructor would. Docs say SFM should automagically find it, but it doesn't appear to. 

Could the issue be one of the columns is UUID? It seems only DataStax supports UUIDs and no other loader. Docs are sparse on how to take say JdbcMapperFactory and add extra conversions for UUID and json columns.

**Comment by DanielJoyce** [comment]
Seems a lot of the API is private final with no public methods to tune construction. Lack of code comments doesn't help either, or examples showing how configuration can be extended .

**Comment by arnaudroger** [comment]
Would you have the error message that it fires? The columns you are trying to map to and their type and how the class is built? I'll have a look.

Static method are looked up the way as constructor if the return type matches the class.

**Comment by arnaudroger** [comment]
I added a test if the of method get resolved
https://github.com/arnaudroger/SimpleFlatMapper/commit/bbc3a1f8c6ed9f08ca510ee849430f28d5540388 
and that works.
if the error you get 
org.sfm.map.MapperBuildingException: Could not find getter for ColumnKey [columnName=bar, columnIndex=2, sqlType=-99999] type class java.util.UUID
 ? then yes it does not know how to get the UUID from the resultset.
I'll add a ticket for it resolve those cases. the work around is to specify a custom getter 


`        final JdbcMapperBuilder<FoobarValue> builder =
                JdbcMapperFactory
                        .newInstance()
                        .addCustomGetter("bar", new Getter<ResultSet, UUID>() {
                            @Override
                            public UUID get(ResultSet target) throws Exception {
                                return UUID.fromString(target.getString("bar"));
                            }
                        })
                        .newBuilder(FoobarValue.class);
`

**Comment by DanielJoyce** [comment]
`
1) Error in custom provider, org.sfm.map.MapperBuildingException: Could not find setter for PropertyMapping{propertyMeta=ConstructorPropertyMeta{owner=class vizualiiz.lightson.data.ImmutableAuditLog, constructorParameter=Parameter{name='id', type=class java.util.UUID, resolvedType=class java.util.UUID}}, columnKey=ColumnKey [columnName=id, columnIndex=1, sqlType=-99999], columnDefinition=ColumnDefinition{}}
  at vizualiiz.lightson.dao.DaoModule.provideAuditLogDao(DaoModule.java:33)
  at vizualiiz.lightson.dao.DaoModule.provideAuditLogDao(DaoModule.java:33)
  while locating vizualiiz.lightson.dao.AuditLogDao
    for parameter 0 at vizualiiz.lightson.service.ServiceModule.providesAuditLogService(ServiceModule.java:28)
  at vizualiiz.lightson.service.ServiceModule.providesAuditLogService(ServiceModule.java:28)
  at vizualiiz.lightson.service.ServiceModule.providesAuditLogService(ServiceModule.java:28)
  while locating vizualiiz.lightson.service.AuditLogService
    for field at vizualiiz.lightson.ServiceTest.logService(ServiceTest.java:30)
  while locating vizualiiz.lightson.ServiceTest
`

Looks like UUID barf.

**Comment by DanielJoyce** [comment]
It can't find a setter, but the class has a static factory method .of() 

  /**
   * Construct a new immutable {@code AuditLog} instance.
   * @param id The value for the {@code id} attribute
   * @param insertedAt The value for the {@code insertedAt} attribute
   * @param log The value for the {@code log} attribute
   * @return An immutable AuditLog instance
   */
  public static ImmutableAuditLog of(UUID id, LocalDateTime insertedAt, JSONObject log) {
    return new ImmutableAuditLog(id, insertedAt, log);
  }

**Comment by DanielJoyce** [comment]
Failing here, when it tries to get the setter for the insert statement

```
    private final JdbcMapperFactory mFactory = JdbcMapperFactory.newInstance().
            addCustomGetter("id", new Getter<ResultSet, UUID>() {
        @Override
        public UUID get(ResultSet target) throws Exception {
            return UUID.fromString(target.getString("id"));
        }
    });

    private final JdbcMapper<ImmutableAuditLog> mapper = mFactory.newMapper(ImmutableAuditLog.class);

//    private final JdbcMapper<ImmutableAuditLog> mapper = mFactory.newMapper(ImmutableAuditLog.class);

    private final String insertQuery = "insert into audit_log(id, log) values (:id,:log)";
    QueryPreparer<ImmutableAuditLog> insertQueryPrep = mFactory.from(ImmutableAuditLog.class).to(NamedSqlQuery.parse(insertQuery));
```

**Comment by DanielJoyce** [comment]
Sorry, trying to track this down better. The API is a bit confusing.

**Comment by DanielJoyce** [comment]
public static factory method for immutable class

```
  /**
   * Construct a new immutable {@code AuditLog} instance.
   * @param id The value for the {@code id} attribute
   * @param insertedAt The value for the {@code insertedAt} attribute
   * @param log The value for the {@code log} attribute
   * @return An immutable AuditLog instance
   */
  public static ImmutableAuditLog of(UUID id, LocalDateTime insertedAt, JSONObject log) {
    return new ImmutableAuditLog(id, insertedAt, log);
  }
```

Traceback I am seeing:

```
org.sfm.map.MapperBuildingException: Could not find setter for PropertyMapping{propertyMeta=ConstructorPropertyMeta{owner=class vizualiiz.lightson.data.ImmutableAuditLog, constructorParameter=Parameter{name='id', type=class java.util.UUID, resolvedType=class java.util.UUID}}, columnKey=ColumnKey [columnName=id, columnIndex=1, sqlType=-99999], columnDefinition=ColumnDefinition{Getter{Getter}}}
	at org.sfm.map.error.RethrowMapperBuilderErrorHandler.accessorNotFound(RethrowMapperBuilderErrorHandler.java:14)
	at org.sfm.map.mapper.ConstantTargetFieldMapperFactorImpl.newFieldMapper(ConstantTargetFieldMapperFactorImpl.java:64)
	at org.sfm.map.AbstractWriterBuilder$2.handle(AbstractWriterBuilder.java:110)
	at org.sfm.map.AbstractWriterBuilder$2.handle(AbstractWriterBuilder.java:105)
	at org.sfm.map.mapper.PropertyMappingsBuilder.forEachProperties(PropertyMappingsBuilder.java:137)
	at org.sfm.map.mapper.PropertyMappingsBuilder.forEachProperties(PropertyMappingsBuilder.java:128)
	at org.sfm.map.mapper.PropertyMappingsBuilder.forEachProperties(PropertyMappingsBuilder.java:124)
	at org.sfm.map.AbstractWriterBuilder.mapper(AbstractWriterBuilder.java:104)
	at org.sfm.jdbc.PreparedStatementMapperBuilder.preparedStatementMapper(PreparedStatementMapperBuilder.java:114)
	at org.sfm.jdbc.PreparedStatementMapperBuilder.to(PreparedStatementMapperBuilder.java:89)
	at org.sfm.jdbc.PreparedStatementMapperBuilder.to(PreparedStatementMapperBuilder.java:81)
	at vizualiiz.lightson.dao.AuditLogDao.insert(AuditLogDao.java:52)

```

Method where it occurs

```
public class AuditLogDao {

    private final JdbcMapperFactory mFactory = JdbcMapperFactory.newInstance().
            addCustomGetter("id", new Getter<ResultSet, UUID>() {
                @Override
                public UUID get(ResultSet target) throws Exception {
                    return UUID.fromString(target.getString("id"));
                }
            });

    private final JdbcMapper<ImmutableAuditLog> mapper = mFactory.newMapper(ImmutableAuditLog.class);

//    private final JdbcMapper<ImmutableAuditLog> mapper = mFactory.newMapper(ImmutableAuditLog.class);
    private final String insertQuery = "insert into audit_log(id, inserted_at, log) values (:id,:insertedAt,:log)";
//    QueryPreparer<ImmutableAuditLog> insertQueryPrep = mFactory.from(ImmutableAuditLog.class).to(NamedSqlQuery.parse(insertQuery));
    private final String findByIdQuery = "select * from audit_log where id = :id";
//    QueryPreparer<ImmutableAuditLog> findByIdQueryPrep = mFactory.from(ImmutableAuditLog.class).to(NamedSqlQuery.parse(findByIdQuery));
    private final String listQuery = "select * from audit_log where id ${comp_op} :id order by id ${order}";

    public void insert(Connection conn, ImmutableAuditLog entity) throws SQLException {
//        NamedSqlQuery.parse(insertQuery);
        QueryPreparer<ImmutableAuditLog> insertQueryPrep = mFactory.from(ImmutableAuditLog.class).to(NamedSqlQuery.parse(insertQuery));
        try (PreparedStatement ps = insertQueryPrep.mapper().map(entity)) {
            int count = ps.executeUpdate();
        }
    }

```

Seems to be trying to find a setter. Am I using the wrong method to try and bind this class to a INSERT?

**Comment by DanielJoyce** [comment]
```
    public void insert(Connection conn, ImmutableAuditLog entity) throws SQLException {
//        NamedSqlQuery.parse(insertQuery);
        QueryPreparer<ImmutableAuditLog> insertQueryPrep = mFactory.from(ImmutableAuditLog.class).to(NamedSqlQuery.parse(insertQuery));  
// ^^^ BARFS here looking for setter for id instead of trying to use static factory method
//        NamedSqlQuery insertQueryPrep = NamedSqlQuery.parse(insertQuery);
//        mFactory.
        try (PreparedStatement ps = insertQueryPrep.prepare(conn).bind(entity)) {
            int count = ps.executeUpdate();
        }
    }
```

**Comment by arnaudroger** [comment]
yes it's the symmetrical ResultSet getter issue but with PreparedStatement setter. and at the minute there is no way to provide a custom setter will add that.

**Comment by arnaudroger** [comment]
is you UUID in the db byte[] or a String?

**Comment by arnaudroger** [comment]
I added a few ticket to deal with all of that, in the mean time the work around would be to define the of method as follow if the source is a String
`
  public static ImmutableAuditLog of(String idAsString, LocalDateTime insertedAt, JSONObject log) {
    return new ImmutableAuditLog(UUID.fromString(idAsString), insertedAt, log);
  }
`
and in the factory 
`
factory.addAlias('id', 'idAsString')
`
that should allow you to get the it to work. I'll add some doc and a a link in the exception to the doc in the future to make it easier to deal with those kind of error

**Comment by arnaudroger** [comment]
just pushed 2.7.6 got UUID for PS setter and RS getter.
