### ISSUE TITLE
support ignore on unknown property

### ISSUE THREAD

**Issue by mumutu** [arnaudroger/SimpleFlatMapper#312]
can make Errors_PROPERTY_NOT_FOUND  just log an warning  instead of throw an exception？

**Comment by arnaudroger** [comment]
You can call igonePropertyNotFound or provide your own mapping error handler or if you are using the mapper factory. If not could you follow specify how you use the mapper?

**Comment by mumutu** [comment]
Thanks for replying  I am using jooq integration 2.9.1 and it seems no any customer config can be injected in to the SfmRecordMapperProvider. whick uses an .so I need rewrite one using my own provider?

**Comment by arnaudroger** [comment]
Yes you are right I'll add a ticket should be able to push one tomorrow where you can do that

**Comment by arnaudroger** [comment]
Ticket already there silly me...

**Comment by mumutu** [comment]
lol  so I should keep this issue open  until you  make it configurable ? or just close it right now?

**Comment by arnaudroger** [comment]
Yes just keep it open I might be able to push something today

**Comment by arnaudroger** [comment]
Ps the ticket was yours, I meant I don't need to open new one

**Comment by mumutu** [comment]
Thanks for your hard working lol

**Comment by arnaudroger** [comment]
I added a factory to give access to the same customization as the other mappers
`
SfmRecordMapperProviderFactory.newInstance().ignorePropertyNotFound().newProvider()
`
instead of - that one still works -
`
new SfmRecordMapperProvider()
`

**Comment by arnaudroger** [comment]
fixed in 2.9.2
