### ISSUE TITLE
Dont do e.printStackTrace()

### ISSUE THREAD

**Issue by rbanikaz** [arnaudroger/SimpleFlatMapper#314]
https://github.com/arnaudroger/SimpleFlatMapper/blob/master/sfm/src/main/java/org/sfm/reflect/impl/ParamNameDeductor.java#L66

The problem is it leads to confusion when this is actually a harmless error which can be ignored.  If this was using a logger we could configure it not to go in the logs but since its going out to stderr there is no way to mask this.  Any suggestions?

**Comment by arnaudroger** [comment]
Thanks for that I don't think it should print anything you are right, must be some left over will have a look asap

**Comment by arnaudroger** [comment]
I'm just gonna remove the printStackTrace, if it can match the name then it will through a can't match name that will need to take from here. As the code in there is doing some speculative getter calling if there is an error it's likely that it's calling the wrong thing

**Comment by rbanikaz** [comment]
Great, thanks!

**Comment by arnaudroger** [comment]
it's fixed in 2.9.4 give it 10-20 minutes to be available in maven central repo
