### ISSUE TITLE
Multiple date formats

### ISSUE THREAD

**Issue by Ramblurr** [arnaudroger/SimpleFlatMapper#330]
I'm using a CsvMapper with the `defaultDateFormat` to specify a format, but I need to be able to specify multiple formats as my input data has varying formats.

Is this possible?

```
  protected CsvMapper<DTOClass> mapper() {
        return CsvMapperFactory
                .newInstance()
                .defaultDateFormat("yyyy-MM-dd")
                .defaultDateFormat("yyyy/MM/dd") /// this overrides the previous line
                .newMapper(DTOClass.class);
    }
```

I should add that I'd rather not add date formats on a per-column basis, because I have quite a few date fields.

**Comment by arnaudroger** [comment]
You can specify the date format at the column level.
See the last paragraph of that
https://github.com/arnaudroger/SimpleFlatMapper/wiki/CsvParser#with-csvmapper

I'll verify that the syntax is still like that later. You can also add a dateformatproperty on the column

**Comment by Ramblurr** [comment]
Yea, so I ended up adding
`.addColumnDefinition("my_date_column", CsvColumnDefinition.dateFormatDefinition("yyyyMMdd"))`

for each date column, however this is more than 20 columns. In general it would be nice to specify multiple default date formats.

**Comment by arnaudroger** [comment]
You can add a property based on a predicate.
http://static.javadoc.io/org.simpleflatmapper/sfm/2.2/org/sfm/map/mapper/AbstractMapperFactory.html#addColumnDefinition-org.sfm.utils.Predicate-CD-

**Comment by arnaudroger** [comment]
Addcolumndefinition( k -> k.getindex() > 1, def)

**Comment by Ramblurr** [comment]
Ah that's great! 

I actually used a regex to match the column names, as it happens that all my date columns have the string "date" in the name.

```java
final Predicate<CsvColumnKey> isDate = csvColumnKey -> {
            final Pattern pat = Pattern.compile(".*date.*", Pattern.CASE_INSENSITIVE);
            return pat.matcher(csvColumnKey.getName()).matches();
        };
 factory
                .addColumnDefinition(appliesTo, dateColumn());
```

And dateColumn():
```java
  protected ColumnDefinition dateColumn() {
        CsvColumnDefinition col = CsvColumnDefinition.dateFormatDefinition(DF1);
        col.addDateFormat(DF2);
        col.addDateFormat(DF3);
        return col;
    }
```
Thanks for the support.

**Comment by arnaudroger** [comment]
Are you having 2 possible format for the same column?

**Comment by Ramblurr** [comment]
Actually it is three possible formats for the same column.

**Comment by arnaudroger** [comment]
Only one format will apply on each definition

**Comment by arnaudroger** [comment]
Yes that's not gonna solve it. I'll have a look when I get access to my computer.

**Comment by Ramblurr** [comment]
thanks @arnaudroger, if you have time I could also use your help in #331

**Comment by arnaudroger** [comment]
so will try to add that feature to allow for multiple format on one column.
in the mean time the best way to solve that would be to provide a custom CellValueReader<Date>

using CsvColumnDefinition.customReaderDefinition

where you try the different format.

**Comment by arnaudroger** [comment]
can you checkout version 2.12 it supports

    CsvColumnDefinition col = CsvColumnDefinition.dateFormatDefinition(DF1);
        col.addDateFormat(DF2);
        col.addDateFormat(DF3);
        return col;
