### ISSUE TITLE
Getting index of row when using stream

### ISSUE THREAD

**Issue by Ramblurr** [arnaudroger/SimpleFlatMapper#331]
When using stream based mapping, how can I get the row of item being processed?

For example I have a `ProcessData` class that processes records via the stream. However if errors are encountered at that point, I want to be able to tell the user which row the data record is.

```java
CsvParser
                .separator(separator).quote(quote)
                .mapWith(csvMapper())
                .stream(reader)
                // how can this process function know the CSV row number?
                .forEach(processData::process); 
```

**Comment by arnaudroger** [comment]
Stream is part of the java api so not much I can do there. What you can do is instead of using method reference you can create an instance of a consumer that keep the currentIndex
```java 
.forEach(new Consumer<T>() {
int currentIndex = 0;
void accept(T t) {
 process(currentIndex, t);
currentIndex++;
}
}); 
```
