### ISSUE TITLE
Comments support

### ISSUE THREAD

**Issue by raipc** [arnaudroger/SimpleFlatMapper#336]
It would be nice if the parser would provide the ability to skip commented lines but store commented line and return it on demand, e.g. by calling reader.getLastComment().

**Comment by arnaudroger** [comment]
is it that for the csv parser? what would a comment line looks like?

**Comment by raipc** [comment]
Yes, it is for CSV parser. Some libraries, for example, Jackson, support it. They define a comment character or sequence (default is "#") which a comment line starts with. Also it would be convenient to provide an tip where the comments can appear: on the top or bottom of the file.

Example:
#This data is generated using $TOOLNAME ON $TIMESTAMP
date,metric,value
2016-09-15,temp,12

**Comment by arnaudroger** [comment]
I would tend to believe that it is only relevant when you use the CsvParser to mapTo an object to avoid failure. 
so what I propose is on mapTo
 - phase 1, when looking for header ignore commented line
 - phase 2, ignore any commented line and callback a another consumer for that.
would that be ok? Or do you need comment handling on the parsing - not to keen on that as the app can deal with it -

**Comment by raipc** [comment]
Actually I don't need mapping to object. I iterate through String[] arrays and need to get the comments at the end. Now I use code like following:
CsvReader reader = CsvParser.reader(new InputStreamReader(inputStream));
Iterator<String[]> iterator = reader.iterator();
while(iterator.hasNext()) {
    processCells(iterator.next());
}

How could it be better to get the comments in this case?

**Comment by arnaudroger** [comment]
you could do something like that.
there is now offical comment spec for csv. 

```java
		Iterator<String[]> iterator = reader.iterator();
		while(iterator.hasNext()) {
			String[] row = iterator.next();
			if (row.length > 0) {
				if (row[0].startsWith("#")) {
					processComment(join(row));
				} else {
					processCells(row);
				}
			}
		}
...

	String join(String[] row) {
		if (row.length == 1) return row[0];
		StringBuilder sb = new StringBuilder();
		for(int i = 0; i < row.length; i++) {
			if (i > 0) sb.append(',');
			sb.append(row[i]);
		}
		return sb.toString();
	}

```

**Comment by raipc** [comment]
It won't work if comments contain JSON.
For example:
#{"errorMessage":"Converting failure", "code":"74"}
will be parsed as ["#{\"errorMessage\":\"Converting failure\", "code:74"].
Second string has cut quotes

**Comment by arnaudroger** [comment]
I see let me think about it

**Comment by raipc** [comment]
I don't control the source of the data, they come as InputStream and may be very large. Copying and manual handling is not the solution

**Comment by arnaudroger** [comment]
it's not trivial because comments are not part of the csv spec. 
so I need to incorporate that so that if one don't have comment one does not pay the price of handling the special case. 
The CellConsumer could handle that with adding a comment callback. 
but then we pollute that interface with that. 

Another solution could be to specify that the parser does not do any unescaping, let the application deal with that, so we can then check on the application side if the row was a comment 
and deal with otherwise do a static call to unescape.

**Comment by raipc** [comment]
Or maybe just get last processed string?

**Comment by arnaudroger** [comment]
it's easier said than done :) for performance purpose it's using a char[] and overwrite the original data on escaping. I'll need a couple of days to come with a prototype

**Comment by raipc** [comment]
OK, thank you

**Comment by arnaudroger** [comment]
Hey just releases a 3.0.b1 version that contains support for yaml comments

the csv parser is now in its own module
```xml
   <dependency>
            <groupId>org.simpleflatmapper</groupId>
            <artifactId>sfm-csv</artifactId>
            <version>3.0.b1</version>
        </dependency>
```

also if you need joda time convertion  you now need to add 

```xml
   <dependency>
            <groupId>org.simpleflatmapper</groupId>
            <artifactId>sfm-converter-joda-time</artifactId>
            <version>3.0.b1</version>
        </dependency>
```

and the package name have change from org.sfm to org.simpleflatmapper to be more compliant with standard package naming.

```java
org.simpleflatmapper.csv.CsvParser
	.dsl()
	.withYamlComments()
        .forEach(reader, (row) -> processRow(row), (comment) -> processComment(comment));
```

it's a beta of 3.0 but it should be pretty stable, 3.0 is a module split plus some restructuring of converters.

Can you try it out and tell me how it goes?

**Comment by arnaudroger** [comment]
@raipc have you had any chance to look at that release?

**Comment by raipc** [comment]
I'm sorry, I haven't tested yet. But now I have replaced the dependency in my pom.xml and project doesn't compile.
<dependency>
        <groupId>org.simpleflatmapper</groupId>
        <artifactId>sfm-csv</artifactId>
        <version>3.0.b1</version>
	<classifier>jdk17</classifier>
</dependency>
gives me following:
[ERROR] Failed to execute goal on project test-sfm: Could not resolve dependencies for project com.raipc:test-sfm:jar:1.0.0-SNAPSHOT: The following artifacts could not be resolved: org.simpleflatmapper:sfm-csv:jar:jdk17:3.0.b1, org.simpleflatmapper:ow2asm:jar:3.0.b1: Failure to find org.simpleflatmapper:sfm-csv:jar:jdk17:3.0.b1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

With jdk16:
[ERROR] Failed to execute goal on project test-sfm: Could not resolve dependencies for project com.raipc:test-sfm:jar:1.0.0-SNAPSHOT: Failure to find org.simpleflatmapper:ow2asm:jar:3.0.b1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by arnaudroger** [comment]
I see I remove the jdk17 artifact, you can use the jdk16 instead - it's the same so removed it -

**Comment by raipc** [comment]
But it still fails with artifact org.simpleflatmapper:ow2asm:jar:3.0.b1

**Comment by arnaudroger** [comment]
that is embedded in the jar, so should not be necessary, I need to change
the pom to be provided.

you'll need to add
that to the dependency.
<exclusions>
  <exclusion>
    <groupId>org.simpleflatmapper</groupId>
    <artifactId>ow2asm</artifactId>
  </exclusion>
</exclusions>

sorry for that, the dep gets build locally on my machine so missed that.
