### ISSUE TITLE
CSVColumnDefinition.compose ignores first definition

### ISSUE THREAD

**Issue by almondtools** [arnaudroger/SimpleFlatMapper#364]
I tried to read a CSV-file with following source code:

    CsvParser
	.skip(1)
	.mapTo(BenchmarkRecord.class)
	.addMapping("Benchmark", compose(renameDefinition("type"), renameDefinition("algorithm")))

My expectation was that the column Benchmark would be mapped to two properties "type" and "algorithm". Maybe this is a misunderstanding of the method `CSVColumnDefinition.compose` - so can you clarify
- if the expectation is correct
- what the purpose of `compose` is
- and how to achieve mapping one csv-column to to properties

**Comment by arnaudroger** [comment]
If i understand properly you want to map the csv column type and algorithm to the benchmark prop in your pojo?
If so you need to add a renameproperty("benchmark") to both type and algorithm.
If not then you want to match benchmark to 2 props I would need to come back to you on that

**Comment by almondtools** [comment]
I made a minimal example, to make it concrete:

The CSV looks like:

    Benchmark, Score
    MyAlgo.forFile, 0.23423
    MyAlgo.forString, 0.13423
    OtherAlgo.forFile, 0.34233
    OtherAlgo.forString, 0.14423
    ....

One could see: The column "Benchmark" contains two parts of information (separated by dot, called algorithm and type)

The target should be a Java class:

     class Record {
      String algorithm;
      String type;
      ....
     }

I tried to do it this way:

    .addMapping("Benchmark", compose(extractType().addRename("type"), extractAlgorithm().addRename("algorithm")))

Where extractType/extractAlgorithm use custom readers to extract the information. These custom readers yet do work, but `compose` does not execute both definitions but only the latter one.

I wondered if this was correct, and if not what is purpose of `compose`.

**Comment by arnaudroger** [comment]
so I would have expecte the following code to work 
```java
        Setter<Data, String> setter = (target, value)  -> {
                int indexOfDot = value.indexOf('.');
                target.algorithm = value.substring(0, indexOfDot);
                target.type = value.substring(indexOfDot + 1, value.length());
            };

        CsvMapper<Data> mapper = CsvMapperFactory
                .newInstance()
                .addColumnProperty("Benchmark", new SetterProperty(setter))
                .newMapper(Data.class);
        CsvParser.mapWith(mapper).stream(DATA).forEach(System.out::println);
```

but it does not because the mapper does not support the SetterProperty. I'll add a seperate ticket to support that.
So currently the only way to make that work would be to have a setBenchmark method that does the split and assigned to the right prop.

```java 
 class Record {
....
        public void setBenchmark(String value) {
                int indexOfDot = value.indexOf('.');
                algorithm = value.substring(0, indexOfDot);
                type = value.substring(indexOfDot + 1, value.length());

        }

}

```

the compose on the field column definition just allow you to fuse 2 definitions. mainly used internally. it does not compose parsing properties for the column.
And right now one column maps to one setter/field.

**Comment by arnaudroger** [comment]
Alternatively if you possible you can put algorithm and type in a Benchmark class with constructor taking a String, or a static factory method.
```java 
class Benchmark {
   String algo;
   String type;

   public static Benchmark valueOf(String str) {
    ....
 } 
} 

class Record {
   Benchmark b;
   double score;
}
```

**Comment by almondtools** [comment]
Thanks for clarifying this issue.

**Comment by arnaudroger** [comment]
no pb, will close that issue.
