### ISSUE TITLE
Join doesn't work when the key JDBC-type maps to an array

### ISSUE THREAD

**Issue by moikarin** [arnaudroger/SimpleFlatMapper#366]
Hi!
I'm working on a legacy Oracle database where some tables use RAW(16) for the primary key. This maps to sqltype -3 (VARBINARY) which ends up as a byte-array in Java.

BreakDetectorImpl.handle() uses Arrays.equals() to detect when the key value has changed. This does not give the desired result when the key value is represented as an array:

```
Object[] lastValues = { new byte[]{4, 5} };
Object[] newValues = { new byte[]{4, 5} };
Arrays.equals(lastValues, newValues);  // returns false
```

--> BreakDetector detects a break on every row and joins do not happen. We can work around this by converting the key to a Stringish type with a SQL function but it would be nice if it worked out of the box.

**Comment by arnaudroger** [comment]
Thanks we'll have a look asap

**Comment by arnaudroger** [comment]
Changing the arrays equals to deep equals does the trick. I should be able t I have a release with the fix overnight

**Comment by arnaudroger** [comment]
should be fixed in version 3.3, just published to maven central, should be available in 1 hour

**Comment by moikarin** [comment]
Thanks for adding this so quickly!
Having a problem using it though - did the dependencies change since sfm-jdbc:3.1 ?
Maven central has objenesis "2.4" but no "2.5s":
```
Could not find org.objenesis:objenesis:2.5s
 Required by: org.simpleflatmapper:sfm-jdbc:3.3 > org.simpleflatmapper:sfm-map:3.3 > org.simpleflatmapper:sfm-reflect:3.3 > org.simpleflatmapper:sfm-converter:3.3

```

**Comment by arnaudroger** [comment]
That's a yes dependency, will double check it's not needed at runtime just to run the test.

**Comment by arnaudroger** [comment]
Yes just checked it's not mark as a test Sep. Will change it and repackage

**Comment by arnaudroger** [comment]
Repushing the jars now. Not very clean but only a Pom change

**Comment by arnaudroger** [comment]
If you can try in a hour with mvn -U

**Comment by arnaudroger** [comment]
3.3 have the right pom now can you check again?

**Comment by moikarin** [comment]
Yes, dependencies are good now. Joins with RAW-columns are working.
Thanks for excellent support!
