### ISSUE TITLE
Support for BigDecimal/BigInteger

### ISSUE THREAD

**Issue by lehoule** [arnaudroger/SimpleFlatMapper#433]
Thanks you for this amazing tool.

Seems like there is no BigDecimalCellValueReader included. Would it be possible to add both of them ? 

Thanks!

**Comment by arnaudroger** [comment]
Sure will have a look tomorrow should be able to have a quick patch release with it

**Comment by lehoule** [comment]
Thanks!

**Comment by arnaudroger** [comment]
I pushed 3.11.6 withe change last night could you check that it works for you?
