### ISSUE TITLE
"Duplicate potential build method" with protobuf generated classes

### ISSUE THREAD

**Issue by jawhiting** [arnaudroger/SimpleFlatMapper#440]
I was trying to map to a protobuf class - figured out how to create a mapper with an explicit builder, but then when it comes to build the final object, it gets a conflict between the "build" method and the "getDefaultInstanceForType" method. As far as I can see there's no way to explicitly specify the build method in the same way that I specified the instantiator method.

`Exception in thread "main" java.lang.IllegalStateException: Duplicate potential build method public com.xyz.MyProto com.xyz.MyProto$Builder.build() and public com.xyz.MyProto com.xyz.MyProto$Builder.getDefaultInstanceForType()
	at org.simpleflatmapper.reflect.impl.BuilderInstantiatorDefinitionFactory.getDefinitionForBuilder(BuilderInstantiatorDefinitionFactory.java:82)
	at org.simpleflatmapper.reflect.impl.BuilderInstantiatorDefinitionFactory.getDefinitionForBuilder(BuilderInstantiatorDefinitionFactory.java:60)
	at org.simpleflatmapper.reflect.ReflectionService.extractInstantiator(ReflectionService.java:206)
	at org.simpleflatmapper.reflect.meta.ObjectClassMeta.<init>(ObjectClassMeta.java:39)
	at org.simpleflatmapper.reflect.ReflectionService.getClassMetaExtraInstantiator(ReflectionService.java:153)
	at org.simpleflatmapper.map.mapper.AbstractMapperFactory.getClassMetaWithExtraInstantiator(AbstractMapperFactory.java:315)
	at org.simpleflatmapper.map.mapper.AbstractMapperFactory.getClassMetaWithExtraInstantiator(AbstractMapperFactory.java:311)
	at com.xyz.MyProtoLoader.main(MyProtoLoader.java:50)`

**Comment by arnaudroger** [comment]
I'll have a look today thanks for the bug report.

**Comment by arnaudroger** [comment]
I'll need to go into more details but have you try 

mapperFactory.newMapper(
    mapperFactory.getClassMetaWithExtraInstantiator(
        IClass.class, 
        MyProto.Bulder.class.getMethod("builder"));

that might work I'll try to confirm on my side but I need to generate some protobuf class.
I also add better testing and support for protobuf to make it work out of the box, I never thought of mapping direclty to proto.

**Comment by arnaudroger** [comment]
so the extra instantiator does not work there, as it still check the one from the class.

**Comment by jawhiting** [comment]
Ah no, that's not quite it - I already do what you've suggested (see below).
The issue is that when you use the builder pattern, the ClassMeta needs **two** methods - the method or constructor to create a new builder instance, and the method to call on the builder to actually create the underlying object.

Taking the approach above allows you to set the method/constructor for creating a new instance of the builder - that works fine with the proto objects. However, what it then does (inside BuilderInstantiatorDefinitionFactory::getDefinitionForBuilder is scan to find that second method - the way to get eg a Security object back out of the builder. As far as I can see there is no way to override that behaviour.

When it comes to protobuf, for whatever reason there are 2 methods that look like they create a builder (so the step above fixes that), but then on the builder there are also 2 methods that look like they create the parent object, and I can't resolve that ambiguity. In proto, the correct one is called "build()", I wonder if you could put in a priority order based on method names?

**Comment by jawhiting** [comment]
To clarify, the various methods seen are:

Instantiators (to create the builder object):
- MyProto.newBuilder()
- MyProto.getDefaultInstance()

Build Methods (to create the original object from the builder):
- MyProto.Builder.build()
- MyProto.Builder.getDefaultInstanceForType()

The instantiator can be specified as shown above, but then it automatically scans for a build method and fails due to the ambiguity there, as there isn't currently a way to explicitly specify the build method too.

**Comment by arnaudroger** [comment]
thanks, just seen that it's the method to build the object that fails. 
ok so I'll fix that, I don't know how yet, maybe if there is a build method that always takes precedence.
or I can make it handle protof code specially and deal with it. Which I prob need to so that we could detect protobuf builder automatically in case of inner object otherwise won't work.

**Comment by jawhiting** [comment]
Yes - there's always a build() method, so naming precedence could work. Otherwise another signature of getClassMetaWithExtraInstantiator that could also take the build method reference.

In terms of proto support - if there was a method name order of preference (eg newBuilder() and build() taking priority), I think it would just work directly. The only reason it didn't already just work was the existence of those getDefaultInstance methods which caused the ambiguity - the inner class was already being handled fine I think.

**Comment by arnaudroger** [comment]
quick question which version of protobuf are you using?

**Comment by jawhiting** [comment]
I'm using proto3, although I'm pretty sure the pattern was the same in proto2. 
Specific library version is 3.2.0.

**Comment by arnaudroger** [comment]
happy days there are a few other issues around handling protobuf collections, and a bug in sub object mapping that does not filter out the uneligible constructor that I need to fix too, I should be able to get a new version in the next few days.

**Comment by arnaudroger** [comment]
@jawhiting so I pushed a few fixes that should make it works, I tested against the csv mapper. Which source are you using? would it be possible for you to test against a local build of master before I do a release?

**Comment by jawhiting** [comment]
I'm using JDBI, so using the SfmResultSetMapperFactory.
I'll do a local build and test against it - probably in the next couple of hours. Thank you!

**Comment by jawhiting** [comment]
I built it locally and tried it out. It seems to get past where it was failing before, so I assume it has correctly detected the instantiator and build methods.
However, I noticed a couple more issues that relate to quirks of protobuf.

1. I had a field of type google.protobuf.Timestamp, which caused it to fail with an error about being unable to locate a getter. I think if the field was called myField of type Timestamp, it was trying to find a method called getMyField on the Timestamp.Builder class. Is there a way to provide explicit type converters to the mapper?
2. Protobuf doesn't like you calling setters with a null value. My source was a database query where some of the columns are null, so it ends up throwing a NullPointerException when this is done.

**Comment by arnaudroger** [comment]
I can add a property to skip setting null, yes it's possible to specify a converter, I'll check later, because depending on the type it should be able to do that automatically

**Comment by jawhiting** [comment]
I figured out how to register a type converter from java.sql.Timestamp to protobuf Timestamp. However, it looks like the mapping failure happens during scanning the class rather than setting the data. Here's the exception:
`Exception in thread "main" org.simpleflatmapper.map.MapperBuildingException: Could not find getter for ColumnKey [columnName=MY_FIELD, columnIndex=59, sqlType=93] type class com.google.protobuf.Timestamp$Builder path myField See https://github.com/arnaudroger/SimpleFlatMapper/wiki/Errors_FMMB_GETTER_NOT_FOUND
	at org.simpleflatmapper.map.error.RethrowMapperBuilderErrorHandler.accessorNotFound(RethrowMapperBuilderErrorHandler.java:20)
	at org.simpleflatmapper.map.mapper.ConstantSourceMapperBuilder$3.handle(ConstantSourceMapperBuilder.java:228)
	at org.simpleflatmapper.map.mapper.ConstantSourceMapperBuilder$3.handle(ConstantSourceMapperBuilder.java:216)
	at org.simpleflatmapper.map.mapper.PropertyMappingsBuilder.forEachConstructorProperties(PropertyMappingsBuilder.java:197)
	at org.simpleflatmapper.map.mapper.ConstantSourceMapperBuilder.constructorInjections(ConstantSourceMapperBuilder.java:216)
	at org.simpleflatmapper.map.mapper.ConstantSourceMapperBuilder.getConstructorFieldMappersAndInstantiator(ConstantSourceMapperBuilder.java:194)
	at org.simpleflatmapper.map.mapper.ConstantSourceMapperBuilder.mapper(ConstantSourceMapperBuilder.java:145)
	at org.simpleflatmapper.map.mapper.AbstractMapperBuilder.mapper(AbstractMapperBuilder.java:57)
	at org.simpleflatmapper.jdbc.JdbcMapperFactory$SetRowMapperFactory.newInstance(JdbcMapperFactory.java:312)
	at org.simpleflatmapper.jdbc.JdbcMapperFactory$SetRowMapperFactory.newInstance(JdbcMapperFactory.java:298)
	at org.simpleflatmapper.map.mapper.DynamicSetRowMapper.getMapper(DynamicSetRowMapper.java:101)
	at org.simpleflatmapper.jdbc.JdbcMapperFactory$DynamicJdbcSetRowMapper.getMapper(JdbcMapperFactory.java:265)
	at org.simpleflatmapper.jdbi.DynamicSfmResultSetMapper.map(DynamicSfmResultSetMapper.java:26)
	at org.skife.jdbi.v2.RegisteredMapper.map(RegisteredMapper.java:35)
	at org.skife.jdbi.v2.ResultSetResultIterator.next(ResultSetResultIterator.java:95)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at com.xyz.MyProto.main(SecurityLoader.java:63)`

**Comment by arnaudroger** [comment]
I'll be able to have a look in a couple of hours

**Comment by arnaudroger** [comment]
You would need to register a getter for that property or split the field to ts_seconds and ts_nanoseconds I think at the minute. Not great

**Comment by arnaudroger** [comment]
I think I'll add google protocol conversion module that can create the ts for date, j.s.Timestamp or long and that should work

**Comment by arnaudroger** [comment]
so I was able to reproduce the problem is that MyProto Builder has 2 methods for Timestamp 
one that takes a Timestamp and one that takes a TimestampBuilder.

**Comment by arnaudroger** [comment]
Alright I pushed more changed could you try again with the last master, and add 

		<dependency>
			<groupId>org.simpleflatmapper</groupId>
			<artifactId>sfm-converter-protobuf</artifactId>
			<version>3.12-SNAPSHOT</version>
		</dependency>

to your pom that contains a Date to protobuf Timestamp converter.

**Comment by arnaudroger** [comment]
Ps null handling stilll missing

**Comment by jawhiting** [comment]
So, it gets past the unable to find getter type error now. However, it looks like there's an issue with the code that reads from the JDBC result set, but only when the target type is the google Timestamp class. For some reason it calls getBinaryStream on the resultset for that column, which then throws an exception - I think maybe because it didn't have a direct mapping for the type, it tries to read the column as bytes and will then convert it later?

Sample code below - if you change the type of MyLocalTest.updateTime to java.util.Date it works, but if you leave it as com.google.protobut.Timestamp it fails. I've tried this against H2 and MySql, so don't think its a driver issue.

import org.simpleflatmapper.jdbi.SfmResultSetMapperFactory;
import org.skife.jdbi.v2.*;

public class SfmProtoTest {
    public static class MyLocalTest {
        public String updateId;
        public com.google.protobuf.Timestamp updateTime;
//        public java.util.Date updateTime;
    }

    public static void main(String[] args) {
        DBI dbi = new DBI("jdbc:h2:mem:test");
        dbi.registerMapper(new SfmResultSetMapperFactory());
        Handle h = dbi.open();
        h.execute("create table MyTable (UPDATE_ID int, UPDATE_TIME datetime)");
        h.execute("insert into MyTable values (1, '2012-09-17 18:47:52.69')");
        h.createQuery("select * from MyTable").mapTo(MyLocalTest.class).forEach(System.out::println);
    }
}

**Comment by arnaudroger** [comment]
did you add the sfm-converter-protobuf to your pom?

**Comment by jawhiting** [comment]
Oh, no I didn't do that - assumed it would come in as a transient dependency. I'll try that now...

**Comment by arnaudroger** [comment]
no same as joda time included only if needed, so if that was not there it
will try to find a way to instantiate, and there is some that take an
inputstream hence the call.

**Comment by jawhiting** [comment]
Ah yes, that sort of fixed it. However, I have some odd, intermittent behaviour.

Is there any parallelisation involved in creating the mapper? I switched the demo class above to use a proto I generated. If I run the exact same code several times in a row, sometimes it works, and sometimes it fails with the same "unable to find getter" error. 
I also noticed that when I run it against a much bigger query (containing multiple date fields), I'll get the error, but it won't be the same column each time, implying there's an ordering or race condition. Do you know what might cause this?
I just ran it 10 times consecutively. If failed 3 times with "Could not find getter", and the other 7 were fine.

**Comment by arnaudroger** [comment]
no parallelisation no.. what's the error? are you running it in the same
thread?

**Comment by arnaudroger** [comment]
I think I was able to reproduce will have a look

**Comment by jawhiting** [comment]
It's the same "Could not find getter" exception that I had above - it's just intermittent. And it happens with the sample program I pasted in above - just create a simple proto file with the same fields as the MyLocalTest inner class.

**Comment by arnaudroger** [comment]
so the problem happens because of the Builder and Timestamp fight for the same property space, the first one to come in - which may vary - will claim the type and exclude the other from gaining getters which then does not get priority

**Comment by arnaudroger** [comment]
so just pushed e last changes so now it should consistently get the right setter and not call setter for null value on builders. could you check ?

**Comment by arnaudroger** [comment]
just pushed version 3.12-rc0 with all the changes, could you check it out?

**Comment by jawhiting** [comment]
Will do in the morning.

**Comment by jawhiting** [comment]
Yes, all seems to work. Null handling, builder and getters for embedded objects all seem to be working fine. Ran it a number of times to try and trigger the inconsistent behaviour and it worked every time.
Thank you!

**Comment by arnaudroger** [comment]
the inconsistent behavior was link to the reflection, getMethods order can
vary and depending on the order it was failing,
I'll push it as 2.12 then, would you know if there might be other type like
timestamp that might be used and need a converter?

**Comment by arnaudroger** [comment]
Thanks again for the report, that made me uncover a few bugs.

**Comment by jawhiting** [comment]
Ah, actually, I was just looking into this. There is a pattern in protobuf where if you have a nullable value for a primitive type (eg a double), they have a wrapper message class (google.protobuf.DoubleValue) that can be null. Now, it's much like the Timestamp class, except that these classes just have a method that's always called setValue, so of course it doesn't match the field name. 

They are listed on [this page](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf)

So, at the moment I was looking at using DoubleValue, Int32Value and Int64Value - looks like converters may be necessary for them - I don't know if they could be handled as a special case instead - if you have an enclose builder that only has one setter with a matching type, maybe that could just be inferred.

**Comment by arnaudroger** [comment]
I'll add a test and try. if sfm detect one param for the builder it will
map it automatically. otherwise will need converter

**Comment by jawhiting** [comment]
Looks like it doesn't work - here's an example for a DoubleValue - it looks like its trying to call "parseDelimitedFrom" to read it directly from the InputStream, whereas really it should go via the standard builder/setValue route.

'Exception in thread "main" java.lang.NullPointerException
	at com.google.protobuf.AbstractParser.parsePartialDelimitedFrom(AbstractParser.java:229)
	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:251)
	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:256)
	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:49)
	at com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(GeneratedMessageV3.java:329)
	at com.google.protobuf.DoubleValue.parseDelimitedFrom(DoubleValue.java:192)
	at org.simpleflatmapper.reflect.generated.com.google.protobuf.AsmInstantiatorDoubleValueFromInputStreamIntoinput_I2.newInstance(Unknown Source)
	at org.simpleflatmapper.reflect.generated.com.google.protobuf.AsmInstantiatorDoubleValueFromInputStreamIntoinput_I2.newInstance(Unknown Source)
	at org.simpleflatmapper.reflect.getter.InstantiatorGetter.get(InstantiatorGetter.java:18)

**Comment by arnaudroger** [comment]
If I make the fall back on the instantiator select builders fisrr it could sort all of these out

**Comment by arnaudroger** [comment]
I pushed a change to filter out method in the builder, the builder becomes eligible as a fallback instantiator with the right kind of affinity so it uses and works

**Comment by arnaudroger** [comment]
just pushed version 3.12 with all of that.
