### ISSUE TITLE
Question, how does it handle large file?

### ISSUE THREAD

**Issue by l7777777b** [arnaudroger/SimpleFlatMapper#448]
Does it read by chunk/line or does it load the whole file into memory or anything else?
Thanks.

**Comment by arnaudroger** [comment]
it processes the file by chunks of 4KB by default, it's changeable by setting a different buffer size. 
but if a cell is bigger than the buffer then it will increase the buffer size to a maximum of the maxBufferSize which is set by default at 8MB.

```java
CsvParser.dsl().bufferSize(1024).maxBufferSize(4096)....
```

**Comment by arnaudroger** [comment]
does that answer the question? reopen if not
