### ISSUE TITLE
Tuple2<int, list> requires elt_0 alias for ont to be mapped

### ISSUE THREAD

**Issue by arnaudroger** [arnaudroger/SimpleFlatMapper#450]

**Comment by arnaudroger** [comment]
tested with query  
```sql 
with t(id, bar) AS (VALUES(1, 'hel'), (1, 'lo'), (2, 'bye')) select * from t
```

```java
		JdbcMapper<Tuple2<Integer, List<Bar>>> mapper = 
				JdbcMapperFactory
						.newInstance()
						.addKeys("id")
						.newMapper(new TypeReference<Tuple2<Integer, List<Bar>>>() {
        });
```

and it worked

**Comment by johnlcox** [comment]
I have two tables as part of a join.

# ResourcePrivilege Join Table:

| resource_id | privilege_id |
| ----------- | ------------|
| 1                  | 10                |
| 2                  | 10                |
| 3                  | 11                |

# Privilege Table:

| id  | name |
| --- | ----- |
| 10  | write |
| 11   | read |

With a select like:
```
select 
  privilege.id, privilege.name, resource_privileges.resource_id
from
  privilege
join resource_privileges on resource_privileges.privilege_id = privilege.id
order by resource_privileges.resource_id
```

I then have mapper code like that only worked once I added "elt_0" and aliased `resource_privileges.resource_id` to "elt_0".

```
JdbcMapper<Tuple2<Integer, List<Privilege>>> privilegeMapper = JdbcMapperFactory.newInstance()
          .addKeys("id")
          .addKeys("elt_0")
          .newMapper(new TypeReference<Tuple2<Integer, List<Privilege>>>() { });
```

**Comment by arnaudroger** [comment]
Thanks will check that in a week

**Comment by arnaudroger** [comment]
I suspect Privilege is 
{
 int id; 
}
?

**Comment by johnlcox** [comment]
Yeah Privilege is basically an id and name:

```Java
class Privilege {
  public int id;
  public String name;
}
```

**Comment by arnaudroger** [comment]
so when the field is no renamed elt0 then it ends up at element1[0].id and privilege_id is mapped to element1[1].id because it matches against the "id" prop name. Also, I discover a bug in my test I only got one privilege for 10 because there is a bug that disables the append for that list #451 

I'll see if I can make the integer field take precedence over the partial match for the first column.

**Comment by arnaudroger** [comment]
could you try with version 3.13rc1 that should work now.
