### ISSUE TITLE
IllegalArgumentException with Play's auto-reload feature

### ISSUE THREAD

**Issue by AlekseyMko** [arnaudroger/SimpleFlatMapper#457]
Hi guys!

I am working on project based on Play framework.
I integrated JOOQ with SimpleFlatMapper.

And there is a problem when auto-reload feature is enabled.
Just after application start SimpleFlatMapper is working properly but after any changes to mapper creation chain I am getting this exception:

```
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.simpleflatmapper.reflect.setter.MethodSetter.set(MethodSetter.java:17)
	at org.simpleflatmapper.map.fieldmapper.FieldMapperImpl.mapTo(FieldMapperImpl.java:24)
	at org.simpleflatmapper.map.generated.models.AsmMapperFromResultSetToSomeDTOInj8_I7.mapFields(Unknown Source)
	at org.simpleflatmapper.map.generated.models.AsmMapperFromResultSetToSomeDTOInj8_I7.mapFields(Unknown Source)
	at org.simpleflatmapper.map.mapper.AbstractMapper.map(AbstractMapper.java:27)
	at org.simpleflatmapper.map.impl.StaticMapperEnumarable.currentValue(StaticMapperEnumarable.java:30)
```

After application restart new code starts work correctly.

It happens for example when I  add or remove addKeys() call

```
JdbcMapperFactory.newInstance()
        .propertyNameMatcherFactory(DefaultPropertyNameMatcherFactory.DEFAULT)
        .addKeys("id")
        .newMapper(SomeDTO.class).stream(resultSet).collect(Collectors.toList());
```

Thank you,
Aleksey

**Comment by arnaudroger** [comment]
Thanks for the report, 
I would assume it's link to a ClassLoader issue with the generated bytecode.
Could you try disabling the asm 
```java
JdbcMapperFactory.newInstance()
        .useAsm(false)
        .propertyNameMatcherFactory(DefaultPropertyNameMatcherFactory.DEFAULT)
        .addKeys("id")
        .newMapper(SomeDTO.class).stream(resultSet).collect(Collectors.toList());
```
and see if that work around will work.
I'll see if I can find a way to check that the class generated where against the right version of the setter and clear the cache if not.

**Comment by AlekseyMko** [comment]
Thanks a lot for so fast response!
Yes, this work around fixes my problem.
Does disabling of asm can cause any performance issues?

**Comment by arnaudroger** [comment]
there will be a slight impact,, but I would be surprise if you see any difference unless you map a set of 100 000 rows from a local db.

Here are some benchmark with the difference strategy with a local mysql
https://github.com/arnaudroger/SimpleFlatMapper/wiki/Jdbc-Performance-Local-Mysql

**Comment by AlekseyMko** [comment]
Thank you!

**Comment by arnaudroger** [comment]
I'll just leave open until the underlying issue is fixed

**Comment by arnaudroger** [comment]
So I played a little bit with play autoreload and it did not fail but if I switch the setter
as in setX set y and setY set x it still called the original one.
which version where you on?

**Comment by AlekseyMko** [comment]
Hello @arnaudroger 

Sorry for the delay
I removed `.useAsm(false)` flag and issue came back
I use the latest version of Play framework (2.6.11 at the moment)

I will prepare a prototype application for you where this issue can be reproduced within a few days

Thanks

**Comment by arnaudroger** [comment]
That be great thanks

**Comment by AlekseyMko** [comment]
Hi @arnaudroger 
I created a test application where you can reproduce IllegalArgument Exception
Please check out my this repo [ https://github.com/AlekseyMko/Play-IllegalArgumentException](https://github.com/AlekseyMko/Play-IllegalArgumentException)
I added steps to reproduce into a README file

BTW there is one more issue you can see with this test app.
I added two articles and some amount of comment entities to the database.
first two comments for an article with id 1 then two for article 2 and last one for article 1
After launching the application you can see **three** articles in resulted json but there only two in database
Looks like for some reason SFM doesn't group records from resultSet if they are not going one by one

Please feel free to ask any additional information

Thank you,
Aleksey

**Comment by arnaudroger** [comment]
Thanks will check it out as soom as I can

**Comment by arnaudroger** [comment]
so I managed to run, 
concerning the duplicate article, it's due to the fact that the query return 

```
| id | text                 | comments_id | comments_article_id | comments_comment | likes_id | likes_article_id |
+----+----------------------+-------------+---------------------+------------------+----------+------------------+
|  1 | article text         |           1 |                   1 | cool!            |        1 |                1 |
|  1 | article text         |           2 |                   1 | hey              |        1 |                1 |
|  2 | enother article text |           3 |                   2 | good             |        2 |                2 |
|  2 | enother article text |           3 |                   2 | good             |        3 |                2 |
|  2 | enother article text |           4 |                   2 | morning          |        2 |                2 |
|  2 | enother article text |           4 |                   2 | morning          |        3 |                2 |
|  1 | article text         |           5 |                   1 | comment          |        1 |                1 |
```
the root object needs to be order for the join to work.
if you add an ORDER BY id it works

**Comment by arnaudroger** [comment]
so was able to reproduce it, and figure out the problem, the asm factory failed to generated the asm setter because for some reason - my own stupidity - it try to generate a primitive setter for Integer. 
so then we have a mix of asm for instantiation and reflection for setter. The asm generation handles the class change with no problem but the reflection points to a method of the previous version.

If you disable asm then you have reflection all the way through so the v1 class is generated.
I fixed the asm setter generation so we can have asm all the way too, which work as well - that explains why I could not reproduce the problem with String too.

I don't know if I'll be able to release in the next 2 days, might be later this week.

**Comment by arnaudroger** [comment]
@AlekseyMko could you check out 3.15.7 it's should be fixed now, thanks for the sample project! helped a lot.

**Comment by AlekseyMko** [comment]
Looks like it's working correctly now
Thank you for the fix and for the explanation about grouping
