### ISSUE TITLE
Ignore null with disabled asm

### ISSUE THREAD

**Issue by AlekseyMko** [arnaudroger/SimpleFlatMapper#458]
Hello.
I use JdbcMapperFactory with disabled asm (because of issu [457](https://github.com/arnaudroger/SimpleFlatMapper/issues/457)) 
I have a POJO with structure like:
```
{
    String id;
    String name;
    List<String> photos;
    List<String> videos;
}
```
And jdbc call which have a few joins and returns ResultSet where potos or videos can have only nulls.

Mapper calls setter for photos and videos if value is null. It could be very annoying as requires additional checks.

I found an issue [445](https://github.com/arnaudroger/SimpleFlatMapper/issues/445) where this was fixed. But seems only for CsvMapperBuilder and other builders where asm is used and turned on.
Also when I checked InstantiatorFactory.java I can see that there is builderBiInstantiator which also has builderIgnoresNullValues flag. But in my case instantiatorDefinition of type CONSTRUCTOR is alway called.

Is there a way to ignor null values with disabled asm?

I failed to find something which can help me in documentation so had to post an issue.

Thank you,
Aleksey

**Comment by arnaudroger** [comment]
I'll check it's likely an oversight on my part

**Comment by arnaudroger** [comment]
PS sorry for the state of the documentation :) any feedback is more than welcome

**Comment by arnaudroger** [comment]
where does the null value endup in the list?  is the problem you get a List of photos with null value in there?

**Comment by arnaudroger** [comment]
can you do a local build? to check something if you open the AppendCollectionSetter and modify the set method to 
```java
    public void set(Collection<E> target, E value) throws Exception {
        if (value != null)
            target.add(value);
    }
```

does that fix the problem? if so it's easy to impl, just need to find a way to pass some config to enable that.

**Comment by arnaudroger** [comment]
just thinking if that's actually the issue then all you should need is to mark the photo and video columns as keys, it should then ignore null values,
PS : the ignore null value is actually for the builder pattern

**Comment by AlekseyMko** [comment]
-  I did a local build with your changes applied to AppendCollectionSetter and it **solved** the problem.
-  I also tried to mark the photo and video columns as keys and this didn't work.
-  As for:
> where does the null value endup in the list? is the problem you get a List of photos with null value in there?
the ignore null value does not apply to constructors because, it will need a value as a param, but because you are talking about the photos and videos I don't think that's the problem here

I have a resault set like in this table

id                  | name              | photos                 | videos
------------ | ------------- | ----------------- | -------------
2                   | trees              | some_photo.jpg   | null
2                   | trees              | some_photo2.jpg | null
4                   | flowers          | null                        | some_video.mpg

And than I have next two POJOs with mapped result:

```
{
    id: 2,
    name: trees,
    photos: [some_photo.jpg, some_photo2.jpg],
    videos: [null, null]
},
{
    id: 4,
    name: flowers,
    photos: [null],
    videos: [some_video.mpg]
}
```

Thank you,
Aleksey

**Comment by arnaudroger** [comment]
happy days, will be able to reproduce and hopefully ship a fix asap

**Comment by AlekseyMko** [comment]
There is one more issue
Solution works great for primitives but don't work for Objects.
I mean if there is a list of some other POJO and ResultSet has nulls for all it's properties
then we will have empty POJO for each aggregated row.

![image](https://user-images.githubusercontent.com/11870760/31398935-468ca796-adf3-11e7-8c59-c2e2e25bac96.png)

**Comment by arnaudroger** [comment]
yes was gonna come to that, so I thought addKey would have work. and it work if you wrap the String in a Media object for example and have a List<Media> instead of String.
The problem is that String is a type return directly from the RS and not a mapped object and the key null check does not apply to it. I'm looking into it.
But workaround at the minute would be to wrap the string in a Media object and mark the columns as key.

**Comment by arnaudroger** [comment]
just put a fix with a test https://github.com/arnaudroger/SimpleFlatMapper/blob/cc43e7bd5cd05e238d218010ec7805bb19448a7b/sfm-jdbc/src/test/java/org/simpleflatmapper/jdbc/test/JdbcMapperListTest.java#L235 that should fix your issue. could you check it out. if that works I'll push it to maven central

**Comment by arnaudroger** [comment]
Just released 3.13.3 to maven central with the fix so that the addKeys works with String/Date etc... could you check it out. should be available in the next 20 minutes

**Comment by AlekseyMko** [comment]
Hi arnaudroger!
I tested your update. Thanks to your test class I modified my mapper initialization chain and got next results.

I added keys for main object and all inner list properties.
```
JdbcMapper<SomeDTO> snapMapper = JdbcMapperFactory.newInstance()
                .useAsm(false)
                .addKeys("id", "photos_name", "videos_name", "comments_id")
                .propertyNameMatcherFactory(DefaultPropertyNameMatcherFactory.DEFAULT)
                .newMapper(SomeDTO.class);
```
I have this ResultSet:

id                  | name              | photos                 | videos            | comments_id | comments_text 
------------ | ------------- | ----------------- | ------------- | ------------- | ---------------
2                   | trees              | some_photo.jpg   | null                 | null                 | null
2                   | trees              | some_photo2.jpg | null                 | null                 | null

- Using SFM version 3.13.2 I have next result:
```
{
    Integer              id: 2,
    String             name: trees,
    List<String>     photos: [some_photo.jpg, some_photo2.jpg],
    List<String>     videos: [],
    List<Comments> comments: null
}
```

- Using SFM version 3.13.3 I have next result:
```
{
    Integer              id: 2,
    String             name: trees,
    List<String>     photos: [some_photo.jpg, some_photo2.jpg],
    List<String>     videos: [],
    List<Comments> comments: []
}
```
As you can see there is only one difference.
In first case (3.13.2) comments = null
In second (3.13.3) comments = [] (empty list) which looks much more reasonable IMO.

NullValueFilterSetter is called **only** when list has key specified.

Probably I could get good result from first case (with 3.13.2) if I being more attentive and added correct keys for lists but I couldn't guess how should they look.

And we always should use keys for lists to avoid duplicates and bunch of null values.

BTW, what do this calls mean?
```
.addMapping("id", 1, 4)
.addMapping("name", 2, 12)
.addMapping("photos_name", 3, 12)
.addMapping("videos_name", 4, 12)
```

**Comment by arnaudroger** [comment]
I used a static mapper in the test, it does not use the ResultSet MetaData to build the Mapper. It makes it easier to debug as you can see what the mapper looks like without to run the query.

Also because it's static it has less overhead, but I don't actually use it in practice just for test.

So it kind of works but I'm actually not really happy yet about the solution. 
The problem is that it will filter out null but not duplicates so if you join 3 tables you might get duplicates in there.
I'm thinking on how to solve that, the path I'm looking at now is for fields that are key, I need to create a mapper that behave the same way as if they were in a Wrapper I think it should be doable.

**Comment by arnaudroger** [comment]
the keys is the way the join mapper will deal with deduplication and null values yes.
prob should add some doc on that :) 
unfortunately right now that's not implemented in the csv mapper.

**Comment by AlekseyMko** [comment]
> The problem is that it will filter out null but not duplicates so if you join 3 tables you might get duplicates in there.

faced duplication problem just now(((
It happens in field like
`List<String> photos`

**Comment by arnaudroger** [comment]
yep more work to be done... will give it a shot tonight.

**Comment by AlekseyMko** [comment]
Thank you.
As a key I have same string as name in result set.
```
.addKeys("id", "photos_filename", "videos_filename", "comments_id")
```

```
s.ID,
photos.field("filename").as("photos_filename"),
videos.field("filename").as("videos_filename"),
comments.field("id").as("comments_id"),
comments.field("comment").as("comments_comment"),
comments.field("timestamp").as("comments_timestamp"
```

Just in case...

**Comment by arnaudroger** [comment]
just pushed a change on master could you try it out with a SNAPSHOT build?

**Comment by arnaudroger** [comment]
just pushed 3.13.4 with a better solution could you check it out?

**Comment by AlekseyMko** [comment]
It works properly now.
Thank you very much 👍

**Comment by arnaudroger** [comment]
you're welcome, hard to anticipate all the cases. will try and reproduce the ClassLoader issue but I have no experience with Play no guarantee on that one :)
