### ISSUE TITLE
Support Kotlin's Pair and Triple

### ISSUE THREAD

**Issue by desiderantes** [arnaudroger/SimpleFlatMapper#482]
Is there any support for Kotlin's `Pair` and `Triple` data types, besides jOOλ's `Tuple2` and `Tuple3`?

**Comment by arnaudroger** [comment]
Not at the minute will have a look at kotlin pair and check it might be trivial to add. Might also check if I can make pluggable for other tuples impl

**Comment by arnaudroger** [comment]
@desiderantes I'm far from familiar with kotlin, do you have a sample project in kotlin I could checkout and play with? to make it happen a bit faster.

**Comment by arnaudroger** [comment]
so just pushed a changed there it looks like the tuple object class meta can recognised the field quite well on the Pair and Triple so only needed to mark them as tuple. Could you try from a snapshot build with the last masteR?

**Comment by arnaudroger** [comment]
Though in my 3 liner sample I did not manage to pass the generic type to Sfm... so it map to a pair of string string

**Comment by arnaudroger** [comment]
alright got it and a test with that

**Comment by arnaudroger** [comment]
just pushed 3.15.4 with a fix to maven central should be available in the next 10-30 mn.

**Comment by desiderantes** [comment]
Whoah sorry! I was offline for a couple of days, what a speedy resolution! Thanks!
