### ISSUE TITLE
MapperBuildingException for nested protobuf objects?

### ISSUE THREAD

**Issue by reiinakano** [arnaudroger/SimpleFlatMapper#484]
This might be related to #440.

I'm trying to map a database record to a nested protobuf object. Database objects are two time columns, namely `start_time` and `end_time`, trying to map to a custom protobuf object composed of two `Timestamp` fields `start` and `end`. 

Using
```java
      JdbcMapperFactory.newInstance()
          .addAlias("start_time", "time_range_start")
          .addAlias("end_time", "time_range_end")
          .newMapper(MyClass.class);
```

or 

```java
      JdbcMapperFactory.newInstance()
          .addAlias("start_time", "time_range.start")
          .addAlias("end_time", "time_range.end")
          .newMapper(MyClass.class);
```

both result in this error
```
Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: org.simpleflatmapper.map.MapperBuildingException: Could not find getter for ColumnKey [columnName=time_range_start, columnIndex=3, sqlType=93] type class com.google.protobuf.Timestamp$Builder path start See https://github.com/arnaudroger/SimpleFlatMapper/wiki/Errors_FMMB_GETTER_NOT_FOUND
```

I noticed a similar error fixed in #440 but could this be the same issue but not fixed for nested objects?

**Comment by arnaudroger** [comment]
Will check it out

**Comment by arnaudroger** [comment]
question do you have the 
```
<dependency>
        <groupId>org.simpleflatmapper</groupId>
        <artifactId>sfm-converter-protobuf</artifactId>
        <version>3.15.4</version>
    </dependency>
```
added ? it deals with PTimestamp conversion.

**Comment by arnaudroger** [comment]
so looking at the error it's taking the Timestamp$Builder setter instead of the Timestamp one.
and that slightly surprising, could you send me the outline - list of methods - of the time_range class?
which version of sfm are you running? and the protobuf version?

**Comment by arnaudroger** [comment]
gonna close that for now, if it's still an issue can you reopen with more details?
