### ISSUE TITLE
Cannot map resultset field to Optional<Instant>

### ISSUE THREAD

**Issue by pawelgosztyla** [arnaudroger/SimpleFlatMapper#486]
Hi,
I'm using SimpleFlatMapper as RecordMapperProvider in Jooq. Looks like it cannot map Timestamp field into Optional\<Instant\> property, it throws an exception:
`org.simpleflatmapper.map.MapperBuildingException: Could not find getter for JooqFieldKey{field="routes"."plannedtransportstarttime", index=2} type ParameterizedTypeImpl{rawType=class java.util.Optional, types=[class java.time.Instant]} path plannedTransportStartTime See https://github.com/arnaudroger/SimpleFlatMapper/wiki/Errors_FMMB_GETTER_NOT_FOUND`

The same issue when trying to map to Optional\<OffsetDateTime\> property.
Regards

**Comment by arnaudroger** [comment]
will have a look.

**Comment by arnaudroger** [comment]
the optional mapping get the constructor injection path in the getter, and it does not currently get the convertion path after that. will see if I can integrate that in there. 
worst case scenario I'll add a Optional converter

**Comment by arnaudroger** [comment]
just pushed version 3.15.6 to maven central, should be available in the next 30 minutes.
It now looks for a converter before trying to find another constructor path.

**Comment by pawelgosztyla** [comment]
Yes, it solved my issue. Thanks @arnaudroger, this was amazingly quick fix!
