### ISSUE TITLE
"with" prefix for builders

### ISSUE THREAD

**Issue by pawelgosztyla** [arnaudroger/SimpleFlatMapper#490]
Hi,
After some experiment I found that SimpleFlatMapper looks for methods prefixed "set" or without prefix when looking for setters in builder.
Is it possible to accept also "with" prefix?
It is used for example as default prefix in Jackson and is accepted by CodeNarc static analysis (in contrast to "set" prefix).

**Comment by arnaudroger** [comment]
yes that should be possible, surprised I did not do it.

**Comment by arnaudroger** [comment]
just pushed 3.15.9 to maven central should be available in the next 20-30 minutes. I add with prefix recognition for builders could you check if that works for you?
Regards, Arnaud

**Comment by pawelgosztyla** [comment]
Yes, its working, thanks!
