### ISSUE TITLE
Mapping does not support fluent setters

### ISSUE THREAD

**Issue by howieB80** [arnaudroger/SimpleFlatMapper#492]
Mapping the  following bean with a fluent setter:

```
class Foo {
    int id;

    public int getId() {
        return id;
    }

    public Foo setId(int id) {
        this.id = id;
        return this;
    }

    public static void main(String[] args) throws IOException {
        CsvParser
                .mapTo(Foo.class)
                .headers("id")
                .forEach("1\n2", System.out::println);
    }
}
```

Gives (on `3.15.9` version):
`Exception in thread "main" java.lang.NoSuchMethodError: sapho.model.Foo.setId(I)V`

Is there any workaround for this?

**Comment by arnaudroger** [comment]
not at the minute, fluent setter are supported for builder, will have a look if we can have that on regular setter.

**Comment by arnaudroger** [comment]
so it's an asm generation issue, the work around is to disable the asm. 
Unfortunately the dsl is not great to do that and you need to create the mapper using the CsvMapperFactory :
```
CsvParser
    .mapWith(
       CsvMapperFactory.newInstance()
           .useAsm(false)
           .newBuilder(Foo.class)
           .addMapping("id").mapper())
    .forEach("1\n2", System.out::println);
```

**Comment by arnaudroger** [comment]
should be able to get a fix released by tomorrow morning UTC

**Comment by howieB80** [comment]
Thanks for quick response! I actually need jdbcMapper, but assume this would work the same (with static mapping)?

**Comment by arnaudroger** [comment]
just put .useAsm(false) on the JdbcMapperFactory and that's it - static mapping or not -.

**Comment by howieB80** [comment]
ok, it works, thanks!

**Comment by arnaudroger** [comment]
just pushed 3.5.10 it should work with the asm generation, could you check?

**Comment by howieB80** [comment]
Works, thanks!
