### ISSUE TITLE
sfm-springjdbc 3.5.10 jdk9 module import issue

### ISSUE THREAD

**Issue by normano** [arnaudroger/SimpleFlatMapper#493]
I'm trying to include sfm-springjdbc jdk9 with gradle and I get error message: module 'XXXX' reads package 'org.springframework.jdbc' from both 'spring.jdbc' and 'spring.jdbc'.

I am using this
implementation (group: 'org.simpleflatmapper', name: 'sfm-springjdbc', version:'3.15.10', classifier: 'jdk9')

I tried to remove all module requires from my module and leave this alone, but the problem persists. I tried to use gradle to exclude the org.springframework pkg from this pkg, but that does not solve the problem.

I can solve the problem when I remove the classifier property since the pkg was compiled with jdk8 using automatic module name without the module-info file. Maybe using transitive is the issue inside of the module-info.

I'll stick with the jdk8 version until the problem is fixed.

**Comment by normano** [comment]
I use intellij and it shows two modules (spring.jdbc and spring.jdbc RELEASE 5.0.4) for some reason only when I import the simpleflatmapper.

List of compile time dependencies from `gradle dependencies` for this particular module since this error is compile time

compileClasspath - Compile classpath for source set 'main'.
+--- project :common
+--- project :metrics
|    \--- project :common
+--- commons-io:commons-io:2.5
+--- org.yaml:snakeyaml:1.17
+--- com.google.guava:guava:23.6-jre
|    +--- com.google.code.findbugs:jsr305:1.3.9 -> 3.0.2
|    +--- org.checkerframework:checker-compat-qual:2.0.0
|    +--- com.google.errorprone:error_prone_annotations:2.1.3
|    +--- com.google.j2objc:j2objc-annotations:1.1
|    \--- org.codehaus.mojo:animal-sniffer-annotations:1.14
+--- com.dslplatform:dsl-json:1.4.0
+--- org.apache.commons:commons-lang3:3.7
+--- org.apache.commons:commons-math3:3.6.1
+--- dk.brics.automaton:automaton:1.11-8
+--- org.magicwerk:brownies-collections:0.9.12
+--- com.lmax:disruptor:3.3.7
+--- commons-cli:commons-cli:1.3.1
+--- uk.com.robust-it:cloning:1.9.2
|    \--- org.objenesis:objenesis:2.1
+--- com.google.code.findbugs:jsr305:3.0.2
+--- org.apache.kafka:kafka-clients:1.0.0
|    +--- org.lz4:lz4-java:1.4
|    +--- org.xerial.snappy:snappy-java:1.1.4
|    \--- org.slf4j:slf4j-api:1.7.25
+--- commons-codec:commons-codec:1.11
+--- org.springframework:spring-jdbc:5.0.4.RELEASE
|    +--- org.springframework:spring-beans:5.0.4.RELEASE
|    |    \--- org.springframework:spring-core:5.0.4.RELEASE
|    |         \--- org.springframework:spring-jcl:5.0.4.RELEASE
|    +--- org.springframework:spring-core:5.0.4.RELEASE (*)
|    \--- org.springframework:spring-tx:5.0.4.RELEASE
|         +--- org.springframework:spring-beans:5.0.4.RELEASE (*)
|         \--- org.springframework:spring-core:5.0.4.RELEASE (*)
+--- org.simpleflatmapper:sfm-springjdbc:3.15.10
|    +--- org.springframework:spring-jdbc:4.3.10.RELEASE -> 5.0.4.RELEASE (*)
|    \--- org.simpleflatmapper:sfm-jdbc:3.15.10
|         \--- org.simpleflatmapper:sfm-map:3.15.10
|              \--- org.simpleflatmapper:sfm-reflect:3.15.10
|                   +--- org.simpleflatmapper:sfm-util:3.15.10
|                   \--- org.simpleflatmapper:sfm-converter:3.15.10
|                        \--- org.simpleflatmapper:sfm-util:3.15.10
+--- com.zaxxer:HikariCP:2.7.8
|    \--- org.slf4j:slf4j-api:1.7.25
\--- net.jodah:typetools:0.5.0

Here is the declared implementation dependencies as well
implementation - Implementation only dependencies for source set 'main'. (n)
+--- commons-io:commons-io:2.5 (n)
+--- org.yaml:snakeyaml:1.17 (n)
+--- com.google.guava:guava:23.6-jre (n)
+--- com.dslplatform:dsl-json:1.4.0 (n)
+--- org.apache.commons:commons-lang3:3.7 (n)
+--- org.apache.commons:commons-math3:3.6.1 (n)
+--- dk.brics.automaton:automaton:1.11-8 (n)
+--- org.magicwerk:brownies-collections:0.9.12 (n)
+--- com.lmax:disruptor:3.3.7 (n)
+--- commons-cli:commons-cli:1.3.1 (n)
+--- uk.com.robust-it:cloning:1.9.2 (n)
+--- com.google.code.findbugs:jsr305:3.0.2 (n)
+--- org.apache.kafka:kafka-clients:1.0.0 (n)
+--- commons-codec:commons-codec:1.11 (n)
+--- org.springframework:spring-jdbc:5.0.4.RELEASE (n)
+--- org.simpleflatmapper:sfm-springjdbc:3.15.10 (n)
+--- com.zaxxer:HikariCP:2.7.8 (n)
\--- net.jodah:typetools:0.5.0 (n)

**Comment by arnaudroger** [comment]
I don't know much about gradle but would it be possible to exclude the spring-jdbc dep from sfm-springjdbc? if that work I'll make it optional and maybe that'll fix it.

**Comment by normano** [comment]
Hmm, no that doesn't work same error. I know if I exclude springframework dependency from the sfm-springjdbc and my pkg then module-info is fine in intellij, so there is some conflict between springjdbc and sfm-springjdbc.

**Comment by arnaudroger** [comment]
Thanks, was worth a try will try to reproduce it, is it a compiler error or runtime ?

**Comment by normano** [comment]
I'm gonna go file a report with Intellij instead. I don't see any problems from java or library side.
