### ISSUE TITLE
Mixed column with same name

### ISSUE THREAD

**Issue by juliendangers** [arnaudroger/SimpleFlatMapper#495]
Hello,

I face an issue with tables sharing similar column names (Kotlin 1.2.30, Spring Boot 2, sfm-jdbc 3.15.11)

**Table1**
idTable1

**TableA**
idTableA
idTable1
something

**TableB**
idTableB
idTableA
variableName
idOperatorCondition
valueCondition

**TableC**
idTableC
idTableA
somethingElse

**TableD**
idTableD
idTableC
variableName
idOperatorCondition
valueCondition

I expect a result of type Pair<Table1, List<Triple<TableA, List<TableB?>, List<Pair<TableC?, List<TableD?>>>>>>

But somehow, sfm try to map columns of tableD to tableB

Here is a test repository https://github.com/juliendangers/simpleflatmapper-495

**Comment by arnaudroger** [comment]
Thanks will have a look

**Comment by arnaudroger** [comment]
pushing the reflection to the max :) btw I would very much like to make it work with that.

**Comment by arnaudroger** [comment]
so that's what I though 
variablename end up being map to 

p1.getPath() = element1[0].element1[0].variableName
p2.getPath() = element1[0].element1[1].variableName
which would be in the same object.
I think we can make it rule out that prop because we have a key on element[x] so  it will be a join.

**Comment by arnaudroger** [comment]
I just pushed a fix on master. your sample app though still fails with an npe, I don't really no why. 
could you check out with a build from master?

I changed the scoring strategy to prefere "lateral" move to "vertical" move so variable name now should end up in the right object.

**Comment by juliendangers** [comment]
Sorry I won't have access to a computer until Sunday, I'll tell you back then. Thanks

**Comment by arnaudroger** [comment]
No worries

**Comment by arnaudroger** [comment]
was missing some null protecting in 
src/main/kotlin/fr/ep/iziglooms/servicetarificationtravaux/calcultarif/domain/dto/AjoutProduitCaracteristiqueDto.kt
-                        ajoutProduitCaracteristique.datemiseajour.toInstant(),
+                        ajoutProduitCaracteristique.datemiseajour?.toInstant(),

and

src/main/kotlin/fr/ep/iziglooms/servicetarificationtravaux/calcultarif/domain/dto/AjoutProduitDto.kt
-                        ajoutProduit.datemiseajour.toInstant(),
+                        ajoutProduit.datemiseajour?.toInstant(),

but seems to work after that. will push it out

**Comment by juliendangers** [comment]
oops sorry about that :(
Anyway it now works like a charm, thanks !
