### ISSUE TITLE
Empty update bad SQL grammar

### ISSUE THREAD

**Issue by EAnushan** [arnaudroger/SimpleFlatMapper#497]
I'm using the JDBCTemplate CRUD and I have a particular table that is composed of only a primary key `id`. Inserts work fine, but trying to run an update:

```
jdbcTemplateCrud.update(entity);
```

I get:

```
org.springframework.jdbc.BadSqlGrammarException: ConnectionCallback; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE id = 48' at line 1
```

The issued statement ends up being something like:
```
UPDATE table_name
SET 
WHERE id = 48
```

Can we ignore updates altogether that modify zero columns (don't run any SQL at all)?

**Comment by arnaudroger** [comment]
thanks for the bug report, will add that.

**Comment by arnaudroger** [comment]
just pushed 3.6.1 to maven central with the fix.
