### ISSUE TITLE
A way to use custom string values to map enums?

### ISSUE THREAD

**Issue by thodt-md** [arnaudroger/SimpleFlatMapper#505]
I have an enum like this:
```
public enum MyEnum {
  DESCRIPTIVE_NAME1("short_code1"),
  DESCRIPTIVE_NAME2("short_code2"),
  ...
  MyEnum(String shortCode) {
     this.shortCode = shortCode;
  }
  ...
  public static MyEnum fromShortCode(String shortCode) {
    // lookup from MyEnum.values() using shortCode
  }
}
```
And a class with `MyEnum` field. The corresponding table column holds `shortCode` values. Is there a way to use `MyEnum.fromShortCode()` when reading the value from the result set? Right now anything I do doesn't seem to have an effect and `org.simpleflatmapper.converter.impl.CharSequenceToEnumConverter.convert()` gets called no matter what. This of course calls `java.lang.Enum.valueOf()` and mapping fails.
I use SFM with JdbcTemplate and tried using both `JdbcTemplateMapperFactory.addColumnDefinition()` and the ServiceLoader/Converter approach.
Any working example on how to achieve this? I imagine this is a fairly common use case, since other libraries like Jackson provide a special way to serialize/deserialize enums not only by their name.

**Comment by arnaudroger** [comment]
I’ll have a look ASAP.

**Comment by arnaudroger** [comment]
Custom getter are set via the the getter property for pull mapper - anything apart from csv for that one it’s a cellvaluereader but I can’t recall the prop

**Comment by arnaudroger** [comment]
just pushed version 3.7.1 
you can now do 

```java
    JdbcTemplateMapperFactory.newInstance()
        .addColumnProperty("my_enum_column", ConverterProperty.of(MyEnum::factoryMethod))
        .newRowMapper(MyDto.class);
```

**Comment by pengisgood** [comment]
I used the version `6.4.0`.

```
public enum UserStatus {
    UNVERIFIED, VERIFIED, DEACTIVATED;

    public static UserStatus fromName(String name) {
        return UserStatus.valueOf(name);
    }
}

JdbcMapper<User> mapper = JdbcMapperFactory
            .newInstance()
            .addColumnDefinition("status",
                FieldMapperColumnDefinition.customGetter((Getter<ResultSet, UserStatus>) rs
                    -> UserStatus.fromName(rs.getString("status"))))
            .newMapper(User.class);

```

I tried the code above, it is not working.

**Comment by arnaudroger** [comment]
which java version? is there any osgi involve? could you copy the stack trace ?

**Comment by pengisgood** [comment]
I updated the previous comment. I used it with Spring Boot and JPA. I suspect it is might be related to my Intellij IDEA hot reload feature.

**Comment by arnaudroger** [comment]
Yes likely a hot reload issue, the asm created its own classloader and it might stick around with the version of the class. Could you try calling useAsm(false) to see if that stop the issue from happening?

**Comment by arnaudroger** [comment]
On the JdbcTemplateMapperFactory

**Comment by neVERberleRfellerER** [comment]
@arnaudroger 
```
java.lang.ClassCastException: com.xx.xxx.domain.UserStatus cannot be cast to com.xx.xxx.domain.UserStatus
```
I've encountered the same problem with Kotlin data classes. It is caused by combination of asm and Spring Boot Devtools. useAsm(false) indeed fixes it. That's all good, but it's quite annoying to set useAsm to false everywhere. Is it safe to reuse result of JdbcTemplateMapperFactory.newInstance() and inject it? Then I could inject one with useAsm set to false without writing a wrapper.

**Comment by arnaudroger** [comment]
Mappers are thread safe and can be safely shared.

**Comment by arnaudroger** [comment]
@neVERberleRfellerER  created issue 623 to see if we can support the dev tools reload

**Comment by arnaudroger** [comment]
6.6.0 is being release at the minute and should work fine now with springboot devtools.

**Comment by neVERberleRfellerER** [comment]
@arnaudroger It really works. Thank you very much.
