### ISSUE TITLE
minimal sfm-csv no longer lightweight

### ISSUE THREAD

**Issue by slandelle** [arnaudroger/SimpleFlatMapper#508]
Until 3.16, if one was only projecting into raw Java structure (Map and List), it was possible to only pull the csv, map and util modules, for a total weight of ~500kb.

Since 3.17 that ships an ASM fork, the reflect module is not required (otherwise AbstractCharConsumer class fails to load with `ClassNotFoundException: org.simpleflatmapper.ow2asm.ClassVisitor`). The total minimal weight is now ~1Mb.

**Comment by arnaudroger** [comment]
We should be able to make that work

**Comment by arnaudroger** [comment]
Are you excluding all the other dep?

**Comment by slandelle** [comment]
I'm explicitly excluding tuples and reflect. Other transitive deps might get excluded this way.

**Comment by arnaudroger** [comment]
That should not be hard, also will try to make it so you don’t need map. But I wonder if more long term it might worth have the pure - no mapTo - csv parsing in its on module or even project.

**Comment by slandelle** [comment]
That's for you to say :)

**Comment by arnaudroger** [comment]
so got it to work without sfm-reflect. for sfm-map it's a bit to tricky at the minute. will add a ticket to have the parse in a separate module.

**Comment by slandelle** [comment]
Thanks @arnaudroger ! Will give it a try as soon as it gets sync'ed on central.

**Comment by slandelle** [comment]
Working great, thanks!
