### ISSUE TITLE
extract csv parser without mapping to its own module

### ISSUE THREAD

**Issue by arnaudroger** [arnaudroger/SimpleFlatMapper#510]
lightning-csv ?

**Comment by arnaudroger** [comment]
extract csv accelaration to external module as quite heavy

**Comment by arnaudroger** [comment]
@slandelle might want to check the last version out, extracted the csv parser into it's own lightning-csv module. should work without the asm dep to reduce its size.
https://search.maven.org/artifact/org.simpleflatmapper/lightning-csv/4.0.0/bundle

76K + sfm-utl 52K

**Comment by arnaudroger** [comment]
1 - yes but you can exclude it it should work without it.
2 - osgi compatibility

**Comment by slandelle** [comment]
1. yes, indeed
2. oh, right

Thanks!
