### ISSUE TITLE
Can you do a one to many mapping with the JDBC template?

### ISSUE THREAD

**Issue by philly51383** [arnaudroger/SimpleFlatMapper#512]

**Comment by arnaudroger** [comment]
Yes you can I probably need to add some doc for that.
you can do one to many with the row mapper as it cannot do aggregation but the JdbcTemplateMapperFactory can return a ResultSetExtractor or PreparedStatementCallBack
```java
	@Test
	public void testPreparedStatementCallback() throws SQLException, ParseException  {
		PreparedStatementCallback<List<DbObject>> mapper = JdbcTemplateMapperFactory.newInstance().newPreparedStatementCallback(DbObject.class);
		List<DbObject> results = template.execute(DbHelper.TEST_DB_OBJECT_QUERY, mapper);
		DbHelper.assertDbObjectMapping(results.get(0));
	}

	@Test
	public void testResultSetExtractor() throws SQLException, ParseException  {
		ResultSetExtractor<List<DbObject>> mapper = JdbcTemplateMapperFactory.newInstance().newResultSetExtractor(DbObject.class);
		List<DbObject> results = template.query(DbHelper.TEST_DB_OBJECT_QUERY, mapper);
		DbHelper.assertDbObjectMapping(results.get(0));
	}
```
that can do that,

I'll keep the ticket open until I add some more documentation.

The spring jdbc support uses the jdbc mapper under it, so it can to anything sfm-jdbc can do. it just provide wrapper for the spring jdbc api.

if that still does not work, could you send me the spring jdbc code you are using.

PS: the keys need to match the column name coming from resultset not the property name - unless you add an alias.

**Comment by arnaudroger** [comment]
also checkout https://arnaudroger.github.io/blog/2017/06/13/jdbc-template-one-to-many.html

**Comment by arnaudroger** [comment]
update doc
