### ISSUE TITLE
Row identifier for CSV errorMappingField

### ISSUE THREAD

**Issue by clamothe** [arnaudroger/SimpleFlatMapper#517]
Is there a way to identify which row a field mapping error occurred for?

I need to display validation errors in my UI if a CSV is not parsable due to field-level errors.
My fallback solution would be to use Strings for every field in my CSV parsing model, as to be permissive, then to validate this object and convert it to a more correctly typed object if validation passes.

That said, it would be great to be able to define the desired types directly on the CSV model (LocalDate, various Enums, etc). If I do so however, I cannot currently catch conversion errors in such a way that both the column and _row_ in error are identified.

Ideally all errors in a particular row would be caught in the first run too, as opposed to short-circuiting parsing of a row once the first field error is encountered. This may be current functionality, I'm not certain.

Thank you!

**Comment by arnaudroger** [comment]
Thanks for the idea, I need to think about it. when we parse the csv it does not have the visibility on the full line, but just see cell by cell. Though we could pass a partially constructed object or the list a constructor args currently build - for constructor injected object, as the information is there in the parser.

**Comment by clamothe** [comment]
I'm accomplishing validation now by having a very permissive CSV model, with all String fields. It has Hibernate Validator annotations on it. If it passes validation, then I convert it to a different class that has more specific types (i.e. LocalDate instead of String)

**Comment by arnaudroger** [comment]
so I've been thinking about it and I came with that prototype 
https://github.com/arnaudroger/SimpleFlatMapper/blob/f0fe0fc9081ab5601cf6a65a555f6def208d1f31/sfm-csv/src/test/java/org/simpleflatmapper/csv/test/CsvMapperImplTest.java#L87

where basically the mapper will not map to the object directly but to a wrapper that will collect the error that occurs during the parsing.

that would be added to the mapper factory as a one call - name undefined now. but would work as in the test.
@clamothe what do you think?

**Comment by arnaudroger** [comment]
will be released part of 4.0.0

**Comment by arnaudroger** [comment]
@clamothe  it's released now
