### ISSUE TITLE
jdbc template crud creation problem when is_enabled column name used

### ISSUE THREAD

**Issue by kanbal** [arnaudroger/SimpleFlatMapper#531]
I have a table with one of columns which is BOOLEAN and is called: `is_enabled`.
In my kotlin application i have data class with the Boolean type field: `isEnabled`.

When I try to create crud JdbcTemplateCrud i got the following error:

> Caused by: org.simpleflatmapper.map.MapperBuildingException: Could not find eligible property for 'is_enabled' on  ... (here my pojo name)

For now I have changed name of the column to: `enabled ` which solves my problem.
Is there any other way to solve this?

BR
marcin

**Comment by arnaudroger** [comment]
I'll have a look thanks for the bug report.

**Comment by arnaudroger** [comment]
could you confirm the kotlin version and the sfm version you are using?

**Comment by arnaudroger** [comment]
so I tried to reproduce with the following code, it's using the CsvMapper but it does go through the same property resolution steps 

```java 
    @Test
    fun test531() {
        val p = CsvParser.mapTo(object : TypeReference<O531>() {}).iterator("is_enabled\ntrue").next();
        println(p);
        println(Arrays.toString(p.javaClass.methods));
    }

    data class O531(var isEnabled: Boolean)
```

and it did work, with val too.

could you run that code and see if it's got the issue? if so could you copy the output of the command line with val and var?

**Comment by arnaudroger** [comment]
Nevermind I missed the crud part

**Comment by arnaudroger** [comment]
was able to reproduce with 

```java
        ClassMeta<O531> classMeta = ReflectionService.newInstance().getClassMeta(O531.class);

        PropertyFinder<O531> propertyFinder = classMeta.newPropertyFinder(new Predicate<PropertyMeta<?, ?>>() {
            @Override
            public boolean test(PropertyMeta<?, ?> propertyMeta) {
                return !NullGetter.isNull(propertyMeta.getGetter());
            }
        });
        propertyFinder.findProperty(DefaultPropertyNameMatcher.of("id"), new Object[0], (TypeAffinity) null);
        PropertyMeta<O531, Object> property = propertyFinder.findProperty(DefaultPropertyNameMatcher.of("is_enabled"), new Object[0], (TypeAffinity) null);

        assertNotNull(property);
```

the getter is linked to the prop "enabled" but the constructor is linked to "isEnabled"
the mapping from rs to object is fine, but from object to ps fails

**Comment by arnaudroger** [comment]
just pushed 3.18.3, could you try it, I added special logic to handle boolean field with constructor injection. that should fix the issue.

**Comment by kanbal** [comment]
Great. I will try this tomorrow.


śr., 27.06.2018, 00:16 użytkownik Arnaud Roger <notifications@github.com>
napisał:

**Comment by kanbal** [comment]
Works fine!
Thank you for quickly solving the issue.

BR
Marcin

2018-06-27 0:56 GMT+02:00 Marcin <marcin0920@gmail.com>:
