### ISSUE TITLE
Converter for javax.money

### ISSUE THREAD

**Issue by davidkarlsen** [arnaudroger/SimpleFlatMapper#537]
is it possible to have Converters which convert two columns into an object?
Like http://jadira.sourceforge.net/apidocs/org/jadira/usertype/moneyandcurrency/joda/PersistentMoneyAmountAndCurrency.html ?

**Comment by arnaudroger** [comment]
basically Money as 2 property currency and amount, so  there should not be any need for a converter
if have col_currency, col_amount on the prop `Money col`
 
the tricky part is : will simpleflatmapper find the right static method to instantiate if it does not that I can had some code to handle that. but I would start there.

**Comment by arnaudroger** [comment]
I’ll add a test to check the behaviour.

**Comment by davidkarlsen** [comment]
I got:
```
org.simpleflatmapper.map.MapperBuildingException: Could not find getter for JooqFieldKey{field="APPDATA"."T_ACCOUNT"."AMOUNT", index=4} type interface javax.money.MonetaryAmount path currencyAndAmount See https://github.com/arnaudroger/SimpleFlatMapper/wiki/Errors_CSFM_GETTER_NOT_FOUND
```

**Comment by arnaudroger** [comment]
Thanks that will help it could not find a way to build a currency amount will have a look

**Comment by davidkarlsen** [comment]
`Money.of(tAccountRecord.getAmount(), tAccountRecord.getCurrencycode())`

**Comment by arnaudroger** [comment]
do you have a currency field in the APPDATA table?

**Comment by arnaudroger** [comment]
looking at the api it will need a bit more work. The MonetaryAmount is created via a factory that is 
I'll see If can figure out a work around.

**Comment by davidkarlsen** [comment]
yes, a currencycode and the amount.

**Comment by arnaudroger** [comment]
so I added a way to register builder on classes, and added the definition for Monetary amount

see test 
https://github.com/arnaudroger/SimpleFlatMapper/blob/master/sfm-jooq/src/test/java/org/simpleflatmapper/jooq/test/Issue537Test.java#L89

the only thing is that in your object currencyCode need to map to currencyAndAmount.currency and 
amount to currencyAndAmount.number - the name of the prop in the factory to that you can as in the test add aliases. Because you have the generated model you can have a more specific target 

```
        SfmRecordMapperProvider recordMapperProvider = SfmRecordMapperProviderFactory
                .newInstance()
                .addColumnProperty( k -> k.getField() == ACCOUNT.AMOUNT, new RenameProperty("currencyAndAmount_number"))
                .addColumnProperty( k -> k.getField() == ACOUNT.CURRENCY_CODE, new RenameProperty("currencyAndAmount_currency"))
                .newProvider();
```

could you try it out? version 3.19.0

**Comment by davidkarlsen** [comment]
Awesome - that worked wonders - thanks a lot!

For the record the resulting code is:
```
 return SfmRecordMapperProviderFactory
                .newInstance()
                    // https://github.com/arnaudroger/SimpleFlatMapper/issues/537:
                    .addColumnProperty( c -> c.getField() == TAccount.T_ACCOUNT.AMOUNT, new RenameProperty("currencyAndAmount_number"))
                    .addColumnProperty( c -> c.getField() == TAccount.T_ACCOUNT.CURRENCYCODE, new RenameProperty("currencyAndAmount_currency"))

                    .addAlias("AMOUNT", "currencyAndAmount_number")
                    .addAlias("currencyCode", "currencyAndAmount_currency")

                    .newProvider()
```
