### ISSUE TITLE
Full support for Kotlin classes

### ISSUE THREAD

**Issue by Infeligo** [arnaudroger/SimpleFlatMapper#538]
Currently SimpleFlatMapper does not properly handle instantiation of Kotlin classes that have fields with default values like this one:

```kotlin
data class CsvLine(
        val field1: String,
        val field2: String,
        val field3: String = "default value"
);
```

See full example in [this repo](https://github.com/Infeligo/simpleflatmapper-kotlin-demo).

I don't know if this helps, but [here](https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/convert/KotlinClassGeneratingEntityInstantiator.java) is how this is handled in Spring Data Common.

**Comment by arnaudroger** [comment]
Cheers will have look

**Comment by arnaudroger** [comment]
I pushed 3.19.0 with support for kotlin's default constructors could you check it out?
