### ISSUE TITLE
Jooq record unmapper

### ISSUE THREAD

**Issue by arnaudroger** [arnaudroger/SimpleFlatMapper#551]

**Comment by arnaudroger** [comment]
https://www.jooq.org/javadoc/3.10.x/org/jooq/class-use/RecordUnmapper.html

**Comment by arnaudroger** [comment]
still in the plan, I'll prob have a look next with another issue. 


you might want to like at model mapper I think  it does that already

DiscriminatorConstantSourceMapperBuilder will be useful to map from record to different object class - like in hibernate discriminator field.

**Comment by hank-cp** [comment]
any clue for **_model mapper_**? I couldn't find anything looks like **_model mapper_**..

**Comment by arnaudroger** [comment]
http://modelmapper.org/

I'll have a look on the unmapper prob in the next few weeks

**Comment by hank-cp** [comment]
> http://modelmapper.org/

I've tried [ModelMapper](http://modelmapper.org/), maybe I am wrong but its type system is much more complicated ant not that clever, that I have to register every single type even if the source and target types are exact the same. So eventually I turn to sfm, which type conversion is much more lint and simple:)

> I'll have a look on the unmapper prob in the next few weeks

Well, thanks very much in advance! I will keep watching on this:)

**Comment by arnaudroger** [comment]
@hank-cp so I had a  look at RecordUnmapper, and the design seem not very friendly for external integration. 
because it relies on the unmapper to create an instance of the record wich require a dsl that is not pass through. 
so in what way were you planning to use it?

**Comment by arnaudroger** [comment]
@hank-cp nevermind I can see a way forward with it, but I don't really know how useful it can be, maybe for inlined object?

**Comment by hank-cp** [comment]
@arnaudroger yes I am planning to use it as the replacement of the `DefaultRecordUnampper`, which doesn't support nested object mapping and custom type conversion. Now I use sfm to do record -> object conversion and I wish the same mapping rule could be applied from object -> record, so I could shared the exact same business model.

**Comment by arnaudroger** [comment]
@hank-cp available in 8.2.0 
```java
cfg.set(JooqMapperFactory.newInstance().newRecordUnmapperProvider(cfg));
```

**Comment by hank-cp** [comment]
@arnaudroger AWESOME~~

I have checked it out but got a little problem. I am using Spring Boot to provide singleton Jooq DSLContext, which will fetch `RecordUnmapperProvider` as singleton bean as well to build the `org.jooq.Configuration`. 

Although `cfg.set(JooqMapperFactory.newInstance().newRecordUnmapperProvider(cfg));` works, but it will required to overwrite lots of Spring Boot code. So I made a PR #694 to decouple 
`RecordUnmapperProvider` and `org.jooq.Configuration`, it could also allow to shared singleton `DSLContext` bean rather than `DSL.using(cfg)` every time for sake of performance. Please kindly review it.

**Comment by arnaudroger** [comment]
Will do, thanks it is an issue that kind of raised to my mind. Also not in the spring boot context

**Comment by arnaudroger** [comment]
Have you tried passing a null config in there? The cfg is only used to instantiate a generic Record object

**Comment by hank-cp** [comment]
> Have you tried passing a null config in there? The cfg is only used to instantiate a generic Record object

Tried. `NullPointerException` raised when trying to new `Record` object.
