### ISSUE TITLE
Error mapping one to many with jdbc template

### ISSUE THREAD

**Issue by rullyalves** [arnaudroger/SimpleFlatMapper#554]
Hello, I tried to use SimpleFlatMapper with Spring JDBC Template, but I get the following error when trying to map a one-to-many relationship "could find eligible property for" price "
my classes are:
public class Category{
private String name;
private String description;
private List<Product> product;
}

public class Product{
private String name;
private String price;
private String description;

....and others....
}

in my database are the same names , help me , please.

**Comment by arnaudroger** [comment]
Hi @rullyalves did you figure out the problem? do you know if there is a way I could make the error message clearer or change the doc to make it easier when that issue happens?
