### ISSUE TITLE
alias does not work

### ISSUE THREAD

**Issue by rullyalves** [arnaudroger/SimpleFlatMapper#555]
Hello, I'm trying to map the following:
public class Category{
private long id;
private String name;
private String description;
private List<subcategory> subcategories;
...other...
}

public class Category{
private long id;
private String name;
private String description;
private List<product> products;
...other...
}

public class Product{
private long id;
private String name;
private String description;
private List<image> images;
...other...
}

My database also contains columns of different tables, like names
I have multiple entities with the same column names and fields in classes, how could I map them correctly?
I tried to give alias to the columns, I tried to use product.id as product_id, however it does not work, I only get the operation up subcategory, from product I get an error saying it could not map the field to the class category, please , help me.

**Comment by arnaudroger** [comment]
Thanks I’ll have. Look ASAP. Could you add one the query you are running that does not map? I assume the class it’s mapping to is the first category object? Was the second one suppose to be subcategory?

**Comment by rullyalves** [comment]
Thanks for the quick response, my query is as follows:
SELECT c.id as id,c.name as name,c.description as description,
s.id as subcategory_id,s.name as subcategory_name,s.description as subcategory_description,
p.id as product_id,p.name as product_name,p.description as product_description,p.price as product_price 
FROM category c 
LEFT OUTER JOIN subcategory s ON s.category_id = c.id 
LEFT OUTER JOIN product p ON p.subcategory_id = s.id 
WHERE restaurant_id = 1 order by c.id";

part of my mapping code :  
ResultSetExtractor<List<Category>> resultSetExtractor = JdbcTemplateMapperFactory.newInstance()
        .addKeys("id","subcategory_id","product_id").newResultSetExtractor(Category.class);
  and error : 
org.simpleflatmapper.map.MapperBuildingException: Could not find eligible property for 'product_id' on  class com.server.entity.Category not found  See https://github.com/arnaudroger/SimpleFlatMapper/wiki/Errors_PROPERTY_NOT_FOUND

my column structure in database:
id,name,description, ....other columns in all tables.

**Comment by arnaudroger** [comment]
so I have not writing any code to reproduce yet, but I think the issue is that 
for product to map to subcatory the name needs to bo subcategories_products_id, subcategories_products_name, subcategories_products_description, subcategories_products_price instead of product_name
we don't yet do speculative discovery on object, we do in list/array on tuples which could help there.
I'll see if we can have rename rules that could rename all the product_ to subcategories_products in one go

**Comment by arnaudroger** [comment]
so if you try 

```java
		JdbcTemplateMapperFactory.newInstance()
				.addKeys("id","subcategory_id","product_id")
				.addColumnProperty(c -> c.getName().startsWith("product_"), new RenameProperty( s -> s.replace("product_", "subcategories_products_")))
				.newResultSetExtractor(Category.class)

```

that should add alias on all the product_ column to have them on the right object

**Comment by rullyalves** [comment]
Hello again, I would like to thank you for the quick response and the solution presents, I got it just by adding: "subcategory_product_id" instead of "product_id" and other fields, thanks for saving me from using an orm hahahaha, lastly, I wonder if I owe this always in nested fields, thank you very much for everything.

**Comment by arnaudroger** [comment]
Yes currently in object it does not look for property in sub object there is a ticket for that but never got around finishing, the problem is that it end up scanning the full property tree which can be quite a lot and needs to add a cyclic type detection. But I night give it another shot.
