### ISSUE TITLE
JDBC Template Mapping for Reading Database Views (Stopped working from 3.18)

### ISSUE THREAD

**Issue by ArminArdekani** [arnaudroger/SimpleFlatMapper#569]
We’ve encountered a problem in sfm-jdbc 3.18+ where we are getting inconsistent sql statements when mapping from jdbc template to Java class using database views for the purpose of search/read. This use to work prior to 3.18.

The error seems to refer to  a mismatch of columns when mapping:
`org.springframework.dao.TransientDataAccessResourceException: ConnectionCallback; Column Index out of range, 12 > 11. ; nested exception is java.sql.SQLException: Column Index out of range, 12 > 11.`

We are using the following for invocation:

```
JdbcTemplateMapperFactory.newInstance()
.crud(Car.class, Long.class)
.lazilyTo(jdbcTemplate(), "car_view")
```

car_view is database view off of a table car with an additional column called car_expenses. Note we are using MYSQL 5.7. Car.class contains property for car_expense.

When we invoke `JdbcTemplateCrud.read(ids, entities::add)`, the last three SQL statements look as follows prior to 3.18:
```
SELECT * FROM car_view WHERE 1 = 2
SHOW KEYS FROM `car` FROM `db`
SELECT * FROM car_view WHERE id in (5)
```

On and after 3.18:
```
SELECT * FROM car_view WHERE 1 = 2
SHOW KEYS FROM `car` FROM `db`
SELECT * FROM car WHERE id in (5)
```

What seems to happen is that the columns from car_view are fetched and when mapping occurs to Car.class, the ResultSet of car is taken and for each column of car_view, the value from the ResultSet is fetched to map to Car.java setters, however once we reach a column from car_view not in car, then we get the Column Index exception.
In this case the column car_expense not being in car table. (Referring to the logic in map.fieldmapper/FieldMapperimpl.java)

To me, the behaviour should be that the three statements should refer to the provided table from the initial invocation, however this is a different case where we are using a database view.

When tracing the code, the problem seems to stem from `org.simpleflatmapper.jdbc.impl.CrudMeta.java:104` where the table name is switched to the one provided by the ResultSetMetadata of the first SQL statement execution. 

ResultSetMetadata.getTableName() is giving back the original table name of the database view which returns car, instead of car_view, thus causing this problem to arise where the third sql statement executes on car.

This use to work correctly prior to 3.18, as this logic was introduced through:
https://github.com/arnaudroger/SimpleFlatMapper/commit/32c065b28787dbc7028aeb2b61668a68370b906c#diff-eea491b882fb1bbbc16ce19475df024f

Through the debugger when changing table to point to car_view instead of car, the mapping works as expected.

According to the logic of java.sql.ResultSetMetadata.getTableName(), there is a flag called useOldAliasMetadataBehavior where if true it will return the alias table name otherwise original table name. Default useOldAliasMetadataBehavior=false.

For MYSQL, this flag can be controlled through a parameter passed through database url however this will cause other problems in the mapping logic where keys are no longer found through the database view.

My question is, are views supported through the mapper or are we suppose to map to database views differently?

Your help in clarifying this is much appreciated.

Thanks :)

**Comment by arnaudroger** [comment]
will have a look thanks for the detailed report!

**Comment by arnaudroger** [comment]
quick question, I'm planning to fix it in the next release 6.0.2 are you happy to upgrade to that. the changes between 3 to 6 are mainly on the mapper producer change so should not need any change.

**Comment by ArminArdekani** [comment]
Yup, that's fine. Thanks for the fast response :)

**Comment by arnaudroger** [comment]
which version of mysql connector are you using?

**Comment by arnaudroger** [comment]
also it looks like from version 3.18.0 it generate the select statement with the column name not the * but I might be mistaken. that would not solve the view problem if the view add a filter on it though. would you mind trying with the last version ?

**Comment by arnaudroger** [comment]
also checkout that test to see if I missed something 

https://github.com/arnaudroger/SimpleFlatMapper/commit/64d24a2ceef868a529de59a6b95da8945a614e82

**Comment by ArminArdekani** [comment]
I'm using mysql connector 6.0.6.

view is declared as:
```
CRETE VIEW car_view AS 
SELECT `c`.*, SUM(.....) AS `car_expenses`
FROM `car` AS `c` LEFT JOIN ...(some other table)
                                   LEFT JOIN ...(some other table)
GROUP BY `c`.`id`
```
All tables are on the same schema.

**Comment by arnaudroger** [comment]
thanks got it, it's the group by that changes mysql behavior ...

**Comment by arnaudroger** [comment]
just pushed 6.0.2 that should have that fixed. could you try it out?

**Comment by ArminArdekani** [comment]
I got this error for the db view after upgrading which makes sense as views don't have keys:
`Caused by: java.lang.IllegalArgumentException: No key defined to map to class java.lang.Long, specify key using DSL or add a primary key to the table`

After adding keys via: `JdbcTemplateMapperFactory.newInstance().addKeys("id").crud(...)...`

It is working! :)

Thanks a lot for your help!
