### ISSUE TITLE
should array/list start the index at 1 or 0?

### ISSUE THREAD

**Issue by arnaudroger** [arnaudroger/SimpleFlatMapper#57]
can it be adapative?

**Comment by arnaudroger** [comment]
Could that be a setup option? At the builder? Property level?

**Comment by a8t3r** [comment]
as i know, in all programming languages index starts from zero

**Comment by arnaudroger** [comment]
I was thinking of that data coming in. for example it's quite common to represent different part of financial product as legs. a curve would a leg1 and leg2. and the data would follow that naming convention.

product_id,leg1_something,leg2_something
