### ISSUE TITLE
sfm-csv do not include null values

### ISSUE THREAD

**Issue by n1b0r** [arnaudroger/SimpleFlatMapper#570]
Hey, 
Thanks for the `sfm-csv` library with its support for nested objects !
I would like to know if it is possible to exclude null values when writting csv ?
This is possible with jackson and json format using the annotation :  `JsonInclude.Include.NON_NULL`.

**Comment by arnaudroger** [comment]
Just to clarify is it so the we put don’t write out the row when the object is null or put an empty cell when a column is null?

**Comment by n1b0r** [comment]
I was meaning that we do not output the column at all.

My case is that I have complex object not fully filled (some attributes are set to null). When using the CsvWriter, every colums are appended but I would like to get only not (fully) null columns.

Is this something possible?

**Comment by arnaudroger** [comment]
not currently, and it would not be trivial to implement and required doing a first pass writing out the csv and then filtering out the empty column, so not cheap and memory intensive.
but doable. On the other hand, if you know which columns have data, you can specify which column to write in the writer 

```
 CsvWriter.from(DbObject.class).columns("id", "name").to(sw)
```

**Comment by n1b0r** [comment]
Thanks for your answer.

I'm trying to create a generic producer for "text/csv" content-type for dropwizard (JAX-RS).
It's working fine, but as my object are not fully loaded (some attributes were not loaded and are null), the outputted csv as a lot of blank values.

I think I will try to do it with some reflexions, but I would have prefered something built in this great library !

Thanks for your time.
