### ISSUE TITLE
SqlParameterSource doesn't recognise ZonedDateTime with simpleJdbcInsert

### ISSUE THREAD

**Issue by AntonKuzValid** [arnaudroger/SimpleFlatMapper#589]
Im using SimpleJdbcInsert - 
@Bean
    fun insertMacAddress(dataSource: DataSource, tablesNames: Map<String, String>) = SimpleJdbcInsert(dataSource)
            .usingGeneratedKeyColumns("day")
            .withTableName(MacAddressRecord::class.getTableName())

and SqlParameterSource - 
@Bean
    fun macAddressSource() = JdbcTemplateMapperFactory.newInstance()
            .ignorePropertyNotFound()
            .addAlias("timestamp_", "timestamp")
            .newSqlParameterSourceFactory<MacAddressRecord>(MacAddressRecord::class.java)!!
 and when i try to insert i got error - 
nested exception is io.crate.shade.org.postgresql.util.PSQLException: Unsuppoerted java.sql.Types type: 2 014
I'm using ZonedDateTime in my model

**Comment by arnaudroger** [comment]
thanks for the bug report will have a look, what is the type of timestamp in the db timestamp? which version of the postgres driver are you using?

**Comment by AntonKuzValid** [comment]
I'm using crateDb. It has JDBC driver build on top of postgres driver, type of column is TIMESTAMP

**Comment by arnaudroger** [comment]
looks like their repackage postgres driver does not support timestamp with tz. 
could you try the following 
```
JdbcTemplateMapperFactory.newInstance()
.ignorePropertyNotFound()
.addAlias("timestamp_", "timestamp")
.addColumnProperty("timestamp", new SqlTypeColumnProperty(Types.TIMESTAMP))
.newSqlParameterSourceFactory(MacAddressRecord::class)
```
that might force it to use the TIMESTAMP, I'll table check that later

**Comment by arnaudroger** [comment]
what the type of timestamp in MacAddressRecord? ZonedDateTime ?

**Comment by AntonKuzValid** [comment]
I have tried it, but result is the same. Yes - ZonedDateTime, and when i manually set paprametrs  convert it to TimeStamp - like this one - 
insertMacAddress.execute(CombinedSqlParameterSource(macAddressRecord,
            mapOf("timestamp_" to macAddressRecord.timestamp.toLocalDateTime().toTimestamp())))

**Comment by arnaudroger** [comment]
ok will create a test for that

**Comment by arnaudroger** [comment]
I should be able to have a fix released tonight, or a workaround. 
I might add a property to indicate the driver is not Jdbc 4.2 compliant

**Comment by arnaudroger** [comment]
so created a small test and it worked.

```java
    @Test
    public void testIssue589() {
        SqlParameterSourceFactory<Issue589> parameterSourceFactory = JdbcTemplateMapperFactory.newInstance()
                .ignorePropertyNotFound()
                .addAlias("timestamp_", "timestamp")
                .addColumnProperty("timestamp_", SqlTypeColumnProperty.of(Types.TIMESTAMP))
                .newSqlParameterSourceFactory(Issue589.class);
        
        ZonedDateTime now = ZonedDateTime.now();
        Issue589 issue589 = new Issue589(now);

        SqlParameterSource sqlParameterSource = parameterSourceFactory.newSqlParameterSource(issue589);
        
        assertEquals(Types.TIMESTAMP, sqlParameterSource.getSqlType("timestamp_"));
        assertEquals(new Timestamp(Date.from(now.toInstant()).getTime()), sqlParameterSource.getValue("timestamp_"));
    }
```

question where is timestamp_ coming from ?
what is the placeholder name in the query? what is the prop name in the object?

**Comment by arnaudroger** [comment]
it's easy to get the column name mixed, I wonder there could be a way to make that easier. 
yep I need to add that somewhere in the long list of docs to write!

**Comment by arnaudroger** [comment]
I just added a bit of documentation https://simpleflatmapper.org/0104-getting-started-springjdbc.html#SqlParameterSource
does that makes sense?
