### ISSUE TITLE
Cannot get alias/one-to-many to work

### ISSUE THREAD

**Issue by barrychapman** [arnaudroger/SimpleFlatMapper#590]
Models:

    class Routes {
        private Integer id;
        private String name;
        private String desc;
    }
    class RoutePath {
        private Integer id;
        private Integer route_id;   // foreign key to Routes 
        private Double lat;
        private Double lng;
    }

      private final RowMapper<Routes> rm = JdbcTemplateMapperFactory.newInstance().newRowMapper(Routes.class);

    /**
     * get a tracking record by record ID
     * @param id - Primary key of Routes record
     * @return Routes
     */
    @Override
    public List<Routes> get(Integer id, Boolean getChildRecords) {
        
        String sql = "SELECT * FROM routes LEFT JOIN `route_path` rp on routes.id = rp.route_id WHERE (`routes`.`id` = ?)";
    
        List<Routes> routes = jdbcTemplate.query(sql, rm);
        return routes;
    }

This yields this error:

    Could not find eligible property for 'route_id' on  class com.wa.shuttle.model.Routes not found  See https://github.com/arnaudroger/SimpleFlatMapper/wiki/Errors_PROPERTY_NOT_FOUND

I do not understand by the documentation that where you take object A and relate it to Object B. Can that be clarified?

**Comment by barrychapman** [comment]
It seems that as though this should be taking two different Mappers to map object A and object B?

**Comment by arnaudroger** [comment]
there is 2 way to do that. you can either add a List<RoutePath> paths in your Routes object, but the column will need to be aliases as in the query to  paths_id, paths_route_id ,paths_lat, path_long.
```java
class Routes {
    private Integer id;
    private String name;
    private String desc; 
    private List<RoutePath> paths;
}

 String sql = "SELECT routes.id as id, routes.name as name, routes.desc as desc,"
+" rp.id as paths_id, rp.route_id as paths_route_id, rp.lat as paths_lat, rp.long as paths_long "
+"FROM routes LEFT JOIN `route_path` rp on routes.id = rp.route_id WHERE (`routes`.`id` = ?)";

```
or you can use a map to a Tuple2<Routes, List<RoutePath>>, you can use sfm-tuples or jools for that.

```java
RowMapper<Tuple2<Routes, List<RoutePath>>> rm = JdbcTemplateMapperFactory.newInstance().newRowMapper(new TypeReference<Tuple2<Routes, List<RoutePath>>> {});
```
like in this example https://arnaudroger.github.io/blog/2017/06/13/jdbc-template-one-to-many.html#what-if-you-want-to-keep-the-role-list-out-of-the-user-object

**Comment by arnaudroger** [comment]
@barrychapman did that help?
