### ISSUE TITLE
NullPointer in newSqlParameterSource when there is unkonown properties in db related #591

### ISSUE THREAD

**Issue by AntonKuzValid** [arnaudroger/SimpleFlatMapper#595]
I upgraded evrsion to - implementation group: 'org.simpleflatmapper', name: 'sfm-springjdbc', version: '6.0.10', and now null pointer in another method  - 

> java.lang.NullPointerException
> 	at org.simpleflatmapper.jdbc.spring.DynamicPlaceHolderValueGetterSource.addColumn(DynamicPlaceHolderValueGetterSource.java:46)
> 	at org.simpleflatmapper.jdbc.spring.DynamicPlaceHolderValueGetterSource.getPlaceHolderValueGetter(DynamicPlaceHolderValueGetterSource.java:30)
> 	at org.simpleflatmapper.jdbc.spring.SqlParameterSourceImpl.hasValue(SqlParameterSourceImpl.java:16)
> 	at org.springframework.jdbc.core.metadata.TableMetaDataContext.matchInParameterValuesWithInsertColumns(TableMetaDataContext.java:219)
> 	at org.springframework.jdbc.core.simple.AbstractJdbcInsert.matchInParameterValuesWithInsertColumns(AbstractJdbcInsert.java:611)
> 	at org.springframework.jdbc.core.simple.AbstractJdbcInsert.doExecute(AbstractJdbcInsert.java:346)
> 	at org.springframework.jdbc.core.simple.SimpleJdbcInsert.execute(SimpleJdbcInsert.java:121)
> 	at ru.evotor.monitor.repository.impl.MacAddressRepositoryImpl.insert(MacAddressRepositoryImpl.kt:41)

I suppose it happens because in **TableMetaDataContext** this method - 
public List<Object> matchInParameterValuesWithInsertColumns(SqlParameterSource parameterSource) should handle with nullPointer exception 
or probably in **DynamicPlaceHolderValueGetterSource** transform this method **PlaceHolderValueGetter<T> getPlaceHolderValueGetter(String column)** to 

> {
> PlaceHolderValueGetterSource<T> ssp = delegate.get();
>             PlaceHolderValueGetter<T> parameter = ssp.getPlaceHolderValueGetter(column);
> return parameter //ignoting check for null
> }

**Comment by arnaudroger** [comment]
Thanks again will look at it

**Comment by arnaudroger** [comment]
just pushed 6.0.11, with better handling of unresolved props hopefully that should be it. should be available in the next 30 minutes
