### ISSUE TITLE
generic character mapping for header

### ISSUE THREAD

**Issue by pgtaboada** [arnaudroger/SimpleFlatMapper#601]
Hi,

I am handling german CSV files, and my alias definitions are always for headers with special characters, like:

ä -> ae
ü -> ue
ß -> ss

It would be nice to be able to add such mappings to the parser.

**Comment by arnaudroger** [comment]
you can easily do that with a RenameProperty with a Function<String, String> applied to all field

```java
C598 c598 = CsvParser.mapTo(C598.class)
		.columnProperty(
			ConstantPredicate.truePredicate(), 
			new RenameProperty(
					str -> str.replaceAll("ä", "ae")
							.replaceAll("ü", "ue")
							.replaceAll("ß", "ss")
			)
		)
		.iterator("geändert\nm").next();	
```

columnProperty can take a column name or a predicate on the CsvColumnKey.
here we said it applies to all.

the rename property can take a Function<String,String> that will do the replace for all column

**Comment by arnaudroger** [comment]
the replaceAll is obviously not the most efficient way to do that. but has it's done only for the headers it should not impact should be minimal, but you can easily write a better version if it needs to be done a lot.

**Comment by arnaudroger** [comment]
@pgtaboada does that solve your problem? or did you have some more specific api idea?

**Comment by arnaudroger** [comment]
Ill close the issue, believing the example is enough
