### ISSUE TITLE
sfm-springjdbc: misparsed parameter name in CTE with newSqlParameterSourceFactory

### ISSUE THREAD

**Issue by neVERberleRfellerER** [arnaudroger/SimpleFlatMapper#625]
When this SQL (minimal broken example) is passed as second argument to newSqlParameterSourceFactory, it will cause bad parse that will keep newline (and eventually FROM) as part of "form_name" and "form_email_address":
```sql
WITH some_cte AS (
    SELECT :form_email_address
    FROM something s
)
SELECT :form_name
FROM something s
```
Same problem happens with joins with condition ending with placeholder and in both (all?) cases it can be workarounded by either putting space after the placeholder or by reordering the columns so placeholder is not at the end of line. With workaround, the order of failures is (when first is fixed, second is encountered):

1. form_name
2. form_email_address

It is necessary to have placeholder in both CTE and outside it. When placeholders are only in CTE or only outside it, it works.

**Comment by arnaudroger** [comment]
Thanks will have a look

**Comment by arnaudroger** [comment]
well that was a silly mistake to not consider \n and \r as sapce ...

**Comment by arnaudroger** [comment]
just pushed 6.6.1 to maven central, should be available in 10-30 min, appears in the search in 2 hours.
