### ISSUE TITLE
Spring jdbc template Could not find eligible property for...

### ISSUE THREAD

**Issue by rullyalves** [arnaudroger/SimpleFlatMapper#626]
Greetings, I'm using Java version 12 and using Simple Flat Mapper to try to map a query that consists of:
products - price_price - prices
products - product_photo - photos

Basically, my query brings all products and their photos and prices (in my system, the price of a product is determined by the state where the buyer lives, and can be variable)
basically, my SQL code is as follows:

  StringBuilder sql = new StringBuilder ("SELECT products.product_id as id, product_name as name,");
        sql.append ("products.product_description as description,");

        sql.append ("product_price_price as price, photo_id, photo_url as product_photo_url from products");
        sql.append ("INNER JOIN product_prices on products.product_id = product_prices.product_id");

        sql.append (
                "LEFT JOIN (photos INNER JOIN product_photos on photos.photo_id = product_photos.product_photos_photo_id)");
        sql.append (
                "ON products.product_id = product_photos.product_photos_product_id WHERE product_prices.state_id =? ORDER BY products.product_id");

And I get the error:

"Could not find eligible property for 'product_photo_url' on class com.prograhma.nutranno.entity.Product not found See https://github.com/arnaudroger/SimpleFlatMapper/wiki/Errors_PROPERTY_NOT_FOUND"
It seems that the simple flat mapper can not identify that the url attribute is from the photo and not from the product, I remember that you answered an issue of mine a long time ago, it was essentially about the same thing, I followed your recommendation, like last time, but this time it did not work.

classes:

public class Product {
    @Key
    private Long id;

    private String name;

    private String description;

    private BigDecimal price;
    @JsonIgnore

    private boolean promotion;

    @JsonIgnore
    private LocalDate created;

    @JsonIgnore
    private LocalDate updated;

    @JsonIgnore
    private boolean status;

    private Collection <Photo> photos;
}

public class Photo {
    @Key
    private Long id;

    @JsonIgnore
    private String name;

    @JsonIgnore
    private String description;

    private String url;
    @JsonIgnore
    private LocalDate created;

    @JsonIgnore
    private LocalDate updated;

}

**Comment by arnaudroger** [comment]
the type on Collection photo is missing  ? is it from that in the original code? or is it Collection<Photo> 
if the type is missing then it won't be able to figure that photos contains object of type photo.

if that's not the problem try to change `as  product_photo_url` to `as product_photos_url` I'm not sure if sfm delete the s.

**Comment by rullyalves** [comment]
No, the photo type in the collection is not empty, I made the exchange that suggested to me, I still get the property error, this may have been caused by some kind of incompatibility with Java 12?

**Comment by arnaudroger** [comment]
Will try and reproduce

**Comment by rullyalves** [comment]
I'm going to try to go back to Java 11 and see if anything changes, if that's fine.

**Comment by arnaudroger** [comment]
could you try with that query :
```StringBuilder sql = new StringBuilder ("SELECT products.product_id as id, product_name as name,");
        sql.append ("products.product_description as description,");

        sql.append ("product_price_price as price, photo_id as photos_id, photo_url as photos_url from products");
        sql.append ("INNER JOIN product_prices on products.product_id = product_prices.product_id");

        sql.append (
                "LEFT JOIN (photos INNER JOIN product_photos on photos.photo_id = product_photos.product_photos_photo_id)");
        sql.append (
                "ON products.product_id = product_photos.product_photos_product_id WHERE product_prices.state_id =? ORDER BY products.product_id");

```

`photo_id as photos_id, photo_url as photos_url`

**Comment by rullyalves** [comment]
Many thanks, worked perfectly, when I must decide if I use the nomenclature: product_photos_id or just photos_id?

**Comment by arnaudroger** [comment]
so the root object is Product so each prop is gonna be name relative to Product as root 
id -> Product.id
photos_id -> Product.photos.id

**Comment by rullyalves** [comment]
So when there are no duplicate names, as in my case, is it safe to use: photos_id instead of product_photos_id? Thank you one more time.
 
I have another doubt, it is related to joins too, in the junction where I should bring only 1 element (product) that contains a collection of nested elements (photos), should I use ResultSetExtractor as well?

**Comment by arnaudroger** [comment]
well so for the naming. if you see your object as a tree with product as a root you get something like this
```
{
 "id" : 1
 "name" : "name"
 "photos" : [ { "id"  : 1 ...}, ...]
}
```
the column name will get match against the path to the property
```
id
name
photos[].id
photos[].name
```
it will ignore some character like _ and do the comparaison ignoring cases, and a few other thing...

the type name `Product` does not come in the path. the root object has no path here. 
so product_photos_id would not match on anything, unless you have a property product in your product object.
