### ISSUE TITLE
jooq.SfmRecordMapperProvider creates empty inner objects

### ISSUE THREAD

**Issue by kjaklik** [arnaudroger/SimpleFlatMapper#627]
Hi,
sorry if issue was already raised, but i was not able to find anything similar.

I'm using sfm-jooq 6.6.1 and jooq 3.11.9
let's say we have a dto:
```
class ExaminationDto {
  private String id;
  private ReferenceDto department;
}

class ReferenceDto {
  private String id;
  private String name;
}
```
and i'm doing a query
```
create
  .select(EXAMINATIONS.ID, DEPARTMENTS.ID.as("department_id"), DEPARTMENT.NAME.as("department_name")
  .from(EXAMINATIONS.leftJoin(DEPARTMENTS).on(EXAMINATION.DEPARTMENT_ID.eq(DEPARTMENTS.ID))
  .where(EXAMINATIONS.ID.eq(id))
  .fetchOneInto(ExaminationDto.class);
```
everything works as expected when examination has department set, but when department is not i would expect to get ExaminationDto object with null department field.
Instead department field is instantiated with null values.
So generally inner object is created even when all columns that map to it have null values.
is it an expected behavior? can it be somehow changed with configuration?

**Comment by arnaudroger** [comment]
could you try adding a `@Key` annotation `org.simpleflatmapper.map.annotation.Key` on the id properties?
then it will consider the object null if its id is null.
if can also be done programatically
```
SfmRecordMapperProviderFactory.newInstance().addColumnProperty("department_id", KeyProperty.DEFAULT).newProvider();
```

**Comment by kjaklik** [comment]
so that would probably work, but I also have inner objects that don't have ids (they are embeds grouping related field) and after adding @Key annotation or adding KeyProperty.DEAFULT, smf starts using BreakDetectorMappingContext instead of MappingContext and it throws IllegalStateException("Invalid state currentKey is null") when mapping that inner object without id

**Comment by arnaudroger** [comment]
humm yes I see let me come to that one in a bit

**Comment by arnaudroger** [comment]
there error relate to #624

**Comment by arnaudroger** [comment]
concerning those grouping related field could you give me an example?

**Comment by kjaklik** [comment]
so about these related fields, extending example from before:

```class ExaminationDto {
  private String id;
  private ReferenceDto department;
  private PatientDto patient;
}

class PatientDto {
  private String name;
  private String species;
  private String owner;
}

class ReferenceDto {
  private String id;
  private String name;
}
```

and now patient data comes directly from examinations table:
```
create
  .select(EXAMINATIONS.ID, 
    DEPARTMENTS.ID.as("department_id"), 
    DEPARTMENT.NAME.as("department_name"), 
    EXAMINTIONS.PATIENT_NAME, 
    EXAMINATIONS.PATIENT_SPECIES, 
    EXAMINTIONS.PATIENT_OWNER)
 
 .from(EXAMINATIONS.leftJoin(DEPARTMENTS).on(EXAMINATION.DEPARTMENT_ID.eq(DEPARTMENTS.ID))
  .where(EXAMINATIONS.ID.eq(id))
  .fetchOneInto(ExaminationDto.class);
```

and to be hones here it's good that mapper creates empty object even when all fields are null, but in case where there is real relation with id it would be nice to have option to make it null when key is null.

So i'm assuming that fixes in #624 should solve this problem of currentKey is null ?

btw. would it be possible to create similar functionality like 
> addColumnProperty("column_name", KeyProperty.DEFAULT)

for field names on object, so instead of having to mark all id fields with @Key annotation, i would just add sth like
> addFieldProperty("id", KeyProperty.DEFAULT)
and all fields with name id would be treated as key fields ?

**Comment by arnaudroger** [comment]
so yes 624 should fix the IllegalStateException, and yes deals ith the department.

so concerning point 2
it's possible to a property based on a predicate

```
.addColumnProperty( k -> k.getName().endsWith("_id"), KeyProperty.DEFAULT)
```
would be the way to solve that right now. 
there is no object based property adding at the minute, as the predicate based one I think is as good. but if you really think it should be added I'll consider it.

**Comment by arnaudroger** [comment]
on the null object when all property is null, I think the behavior is ok now, from a Object mapping perspective it would be weird to have a null object on patient when there is an actual row in the db for it.
If one would want to null those kind of object I would suggest use a factory method for on the object that would return null if all the field are null.
but then if the use case it's strong I can have a look at it - though it might not be trivial to implement.

**Comment by arnaudroger** [comment]
@kjaklik closing the ticket if there still something that needs addressing please reopen
