### ISSUE TITLE
ErrorCollectingMapper doesn't use the specified defaultDateFormat

### ISSUE THREAD

**Issue by saiar** [arnaudroger/SimpleFlatMapper#657]
Hi,

While going through the code I found that there is something called as `ErrorCollectingMapper` in `CsvMapperFactory.java`.

I find that this behaves differently when compared to the standard mapper that we get by calling `CsvMapperFactory.newMapper(...)` when it comes to `LocalDate`. While this mapper seems to take the `CsvMapperFactory.defaultDateFormat(...)` into consideration while parsing dates, the ErrorCollectingMapper doesn't use it and relies on the default defined within the factory, which happens to be ""yyyy-MM-dd HH:mm:ss".

`
      CsvMapperFactory
                .newInstance()
                .defaultDateFormat("yyyy-MM-dd")
                .newMapper(MyObject.class);
`
works fine, but:
`
      CsvMapperFactory
                .newInstance()
                .defaultDateFormat("yyyy-MM-dd")
                .newErrorCollectingMapper(MyObject.class);
`
doesn't.

I found that there is a related [issue here](https://github.com/arnaudroger/SimpleFlatMapper/issues/511).

I was able to use the fix suggested in that thread, which was to use it as follows:

`
      CsvMapperFactory
                .newInstance()
                .addColumnProperty("scheduled_date", new DateFormatProperty("yyyy-MM-dd"))
                .newErrorCollectingMapper(MyObject.class);
`

**Comment by arnaudroger** [comment]
Thanks for the report will have a look

**Comment by saiar** [comment]
Sure. Thanks!
