### ISSUE TITLE
Document how to exclude the jOOQ Open Source Edition as a transitive dependency, when needed

### ISSUE THREAD

**Issue by lukaseder** [arnaudroger/SimpleFlatMapper#659]
Currently, it seems that `SimpleFlatMapper` has a transitive compile time dependency on some version of the jOOQ Open Source Edition, which is nice for new projects, but can get in the way when:

- People want to use newer versions of jOOQ than what `SimpleFlatMapper` depends upon
- People use the commercial distributions of jOOQ (see https://stackoverflow.com/q/56546414/521799)

Perhaps it would be useful to either:

- Make the jOOQ dependency `provided`
- Explain in the docs how to exclude the transitive dependency, to make people aware of how it works: https://simpleflatmapper.org/0106-getting-started-jooq.html

**Comment by arnaudroger** [comment]
I think provided makes sense

**Comment by lukaseder** [comment]
Indeed, especially since in the case of `SimpleFlatMapper`, the two dependencies (SFM and jOOQ) are both quite independent of one another and can both live without the other, so it is likely the user will want to depend on both explicitly...

**Comment by arnaudroger** [comment]
also you are more likely to already have jooq, spring jdbc or any other 
I meant to do that at some point just never got to tidy that up ...
