### ISSUE TITLE
Discriminator on 2 different hierarchy same root type

### ISSUE THREAD

**Issue by arnaudroger** [arnaudroger/SimpleFlatMapper#679]
test2AssFieldWithSameTypeWithDifferentColumnAndDifferentType

**Comment by LukasHaken** [comment]
I have blocker with this problem. Can I lobbing for this isseu?

**Comment by arnaudroger** [comment]
just put in in 8.2.0 miletstone as a reminder to look at it in the bunch of next issues

**Comment by arnaudroger** [comment]
@LukasHaken that should be fixed in the last 8.2.0 release
