### ISSUE TITLE
Custom string separator for csv parser

### ISSUE THREAD

**Issue by Dam14n** [arnaudroger/SimpleFlatMapper#684]
Hey there,

I'm trying to use CSVParser in order to parse a file to a model that follows the convection of a CSV file but using a custom separator. For instance, in this case the separator used into the file is  "~!~" and reading the documentation the way to set a custom separator is:

![image](https://user-images.githubusercontent.com/7736887/66481860-2a68d800-ea78-11e9-9a42-78ab76cc781a.png)

But as you can see it only accepts char, is there a way to set a string as a custom separator like that? 

Regards

**Comment by arnaudroger** [comment]
Not currently only support one char separator.
It would not be a trivial change either.

**Comment by Dam14n** [comment]
Ok , no problem. It was just to confirm. Thanks!
