### ISSUE TITLE
Csv Writer easier to write Iterable<? extends CharSequence[]>

### ISSUE THREAD

**Issue by arnaudroger** [arnaudroger/SimpleFlatMapper#686]

**Comment by ryanthara** [comment]
I have coordinate based inputs which are stored in `List<String[]>` and it would be great to use them directly with CsvWriter class.

**Comment by arnaudroger** [comment]
@ryanthara just pushed new version for a List<String[]> the code would look likethat

try(ClosableCsvWriter writer = CsvWriter.dsl().to(file)) {
   list.forEach(writter::appendRow);
}

the new CsvWriter is in package org.simpleflatmapper.lightningcsv.CsvWriter, not the same as the one in org.simpleflatmapper.csv

**Comment by ryanthara** [comment]
Sounds good.

When will it be available via maven?

**Comment by arnaudroger** [comment]
it's there
https://repo1.maven.org/maven2/org/simpleflatmapper/lightning-csv/8.1.0/

**Comment by ryanthara** [comment]
I checked this [site](https://mvnrepository.com/artifact/org.simpleflatmapper/lightning-csv) here.

Still 8.0.3, but with your link @arnaudroger everything works fine.

**Comment by ryanthara** [comment]
I took a look for it at this [site](https://mvnrepository.com/artifact/org.simpleflatmapper/lightning-csv).

You are wright @arnaudroger.

**Comment by arnaudroger** [comment]
That’s a clone of maven central always a bit late.

**Comment by ryanthara** [comment]
@arnaudroger 

Some addition, maybe for other users too.

`try(ClosableCsvWriter writer = CsvWriter.dsl().to(file)) {
    list.forEach(writer::appendRow);
}`

has to be changed to

`try (ClosableCsvWriter writer = CsvWriter.dsl().to(path.toFile())) {
            csv.forEach(values -> {
                try {
                    writer.appendRow(values);
                } catch (IOException e) {
                   // do whatever you want
                }
            });
        } catch (IOException e) {
            // do whatever you want
        }`

You have to try catch every element of the forEach-loop.

**Comment by arnaudroger** [comment]
you can try also

```java
try(ClosableCsvWriter writer = CsvWriter.dsl().to(file)) { 
    list.forEach(CheckedConsumer.toConsumer(writer::appendRow)); 
}
```

that should work

**Comment by ryanthara** [comment]
@arnaudroger +1

Works like a charm.
