### ISSUE TITLE
GraalVM native image support

### ISSUE THREAD

**Issue by morki** [arnaudroger/SimpleFlatMapper#718]
Will be GraalVM native image supported? It seems ASM is problematic.

**Comment by arnaudroger** [comment]
I have not tried, the asm generation can be disabled, and the asm scanning of class is not madatory.
so in theory it could be made to work

**Comment by morki** [comment]
@arnaudroger sorry, It seems it `JdbcMapper` works well in graal native. The issues I saw was probably JOOQ related. If I found something new, I will reopen. Thank you.
